<?php

/**
 * @file
 * Contains nerdcustom.module..
 */

use \Drupal\node\NodeInterface;

 function nerdcustom_node_links_alter(array &$links, NodeInterface $entity, array &$context) {


if ($entity->bundle() === 'person') {


   $links['node']['#links']['node-readmore'] = array(
     'title' => t('Full bio, podcast clips and links<span class="visually-hidden"> for @title</span>', array(
       '@title' => $node_title_stripped,
     )),
     'url' => $entity->urlInfo(),
     'language' => $entity->language(),
     'attributes' => array(
       'rel' => 'tag',
       'title' => $node_title_stripped,
     ),
   );

} else {

  if (!empty($links['node']['#links']['node-readmore'])) {
    unset ($links['node']['#links']['node-readmore']);
  }
}

 }
