name: nerdologues-composer
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: nerdologues-composer
  id: f8b6bd4b-bde6-45de-b354-3bf2c6c1f757
services:
  appserver:
    overrides:
      services:
        environment:
         BEHAT_PASS_ADMIN: BEHAT_PASS_ADMIN
         BEHAT_USER_ADMIN: BEHAT_USER_ADMIN
         BEHAT_PASS_CONTENT_ADMIN: BEHAT_PASS_CONTENT_ADMIN
         BEHAT_USER_CONTENT_ADMIN: BEHAT_USER_CONTENT_ADMIN

events:
  post-db-import:
    - appserver: "drush user-create $BEHAT_USER_ADMIN --password=$BEHAT_PASS_ADMIN && drush user-add-role administrator $BEHAT_USER_ADMIN && drush user-create $BEHAT_USER_CONTENT_ADMIN --password=$BEHAT_PASS_CONTENT_ADMIN && drush user-add-role content_administrator $BEHAT_USER_CONTENT_ADMIN                  "

tooling:
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat --config=tests/behat/behat-lando.yml
