Feature: Podcast Episode

  @api
  Scenario: Podcast Episode
    Given I am logged in as a user with the "administrator" role
    When I visit "admin/content-migration/podcast_episode"
    Then I should see the following table portion
    | Title                                                                                               | Date Published | Podcast                               | Podbean mp3                                                                                   | Link | Patreon link |
    | October 2013: 1993, Part 2                                                                          | 2013-10-28     | Your Stories                          | http://yourstories.podbean.com/mf/feed/fswtk/October2013Part2.mp3                             |      |              |
    | October 2013: 1993, Part 1                                                                          | 2013-10-14     | Your Stories                          | http://yourstories.podbean.com/mf/feed/vm3hy/October2013Part1.mp3                             |      |              |
    | September 2013 Bonus: First Times (live from the Jangleheart Circus!)                               | 2013-09-26     | Your Stories                          | http://yourstories.podbean.com/mf/feed/tma6ty/Jangleheart.mp3                                 |      |              |
    | September 2013: Best-Laid Plans, Part 2                                                             | 2013-09-23     | Your Stories                          | http://yourstories.podbean.com/mf/feed/c7nxrt/September2013Part2.mp3                          |      |              |
    | September 2013: Best-Laid Plans, Part 1                                                             | 2013-09-09     | Your Stories                          | http://yourstories.podbean.com/mf/feed/2x82e/September2013Part1.mp3                           |      |              |
    | It’s the First of the Month - Where’s Your Stories?                                                 | 2013-09-01     | Your Stories                          |                                                                                               |      |              |
    | August 2013: Games, Part 2                                                                          | 2013-08-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/fpsx5u/August2013Part2.mp3                             |      |              |
    | August 2013: Games, Part 1                                                                          | 2013-08-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/xy56t4/August2013Part1.mp3                             |      |              |
    | July 2013 Bonus: Superman                                                                           | 2013-07-22     | Your Stories                          | http://yourstories.podbean.com/mf/feed/626ehb/Superman.mp3                                    |      |              |
    | July 2013: Indie, Part 2                                                                            | 2013-07-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/c3b4gw/July2013Part2.mp3                               |      |              |
    | BONUS: Freedom Isn’t Free                                                                           | 2013-07-04     | Your Stories                          | http://yourstories.podbean.com/mf/feed/ynz98/FreedomIsntFree.mp3                              |      |              |
    | July 2013: Indie, Part 1                                                                            | 2013-07-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/ak3ev3/July2013Part1.mp3                               |      |              |
    | June 2013: Journey, Part 3                                                                          | 2013-06-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/g9su96/June2013Part3.mp3                               |      |              |
    | June 2013: Journey, Part 2                                                                          | 2013-06-08     | Your Stories                          | http://yourstories.podbean.com/mf/feed/6x4iw7/June2013Part2.mp3                               |      |              |
    | June 2013: Journey, Part 1                                                                          | 2013-06-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/5e8dd5/June2013Part1.mp3                               |      |              |
    | May 2013: Crime and Punishment, Part 3                                                              | 2013-05-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/if68nh/May2013Part3.mp3                                |      |              |
    | May 2013: Crime and Punishment, Part 2                                                              | 2013-05-08     | Your Stories                          | http://yourstories.podbean.com/mf/feed/ry7e49/May2013Part2.mp3                                |      |              |
    | May 2013: Crime and Punishment, Part 1                                                              | 2013-05-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/rcz688/May2013Part1.mp3                                |      |              |
    | April 2013 Bonus: Madness Online + Star Trek Rock                                                   | 2013-04-25     | Your Stories                          | http://yourstories.podbean.com/mf/feed/frqmyb/April2013Online.mp3                             |      |              |
    | April 2013: Madness, Part 2                                                                         | 2013-04-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/39frmn/April2013Part2.mp3                              |      |              |
    | April 2013: Madness, Part 1                                                                         | 2013-04-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/j7gwmp/April2013Part1.mp3                              |      |              |
    | March 2013 Online: Fanfiction (The End)                                                             | 2013-03-22     | Your Stories                          | http://yourstories.podbean.com/mf/feed/cbeu56/March2013Online.mp3                             |      |              |
    | March 2013 Bonus: THE STARTUP                                                                       | 2013-03-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/ehtyhd/Startup.mp3                                     |      |              |
    | March 2013: Fanfiction, Part 2                                                                      | 2013-03-08     | Your Stories                          | http://yourstories.podbean.com/mf/feed/uxkzw7/March2013Part2.mp3                              |      |              |
    | March 2013: Fanfiction, Part 1                                                                      | 2013-03-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/yjvvkd/March2013Part1.mp3                              |      |              |
    | February 2013 Online: Ch-Ch-Ch-Ch-Changes                                                           | 2013-02-22     | Your Stories                          | http://yourstories.podbean.com/mf/feed/uss7uv/Feb2013Online.mp3                               |      |              |
    | February 2013 Part 2: Reboot                                                                        | 2013-02-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/94rnsg/Feb2013Part2.mp3                                |      |              |
    | February 2013 Part 1: A New Hope                                                                    | 2013-02-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/y58vdu/Feb2013Part1.mp3                                |      |              |
    | Announcing YOUR STORIES ONLINE                                                                      | 2013-01-25     | Your Stories                          |                                                                                               |      |              |
    | January 2013 Part 2: Rando                                                                          | 2013-01-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/253srk/January2013Part2128.mp3                         |      |              |
    | The Internet Song (ft. Claire Friedman & Eric Garneau)                                              | 2013-01-04     | Your Stories                          | http://yourstories.podbean.com/mf/feed/bw4vh/InternetSong.mp3                                 |      |              |
    | January 2013 Part 1: Mixed Bag                                                                      | 2013-01-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/izhnmq/January2013Part1.mp3                            |      |              |
    | Best of 2012: Audience Picks                                                                        | 2012-12-31     | Your Stories                          | http://yourstories.podbean.com/mf/feed/vccaey/2012BestOf.mp3                                  |      |              |
    | Best of 2012: Producer’s Picks                                                                      | 2012-12-24     | Your Stories                          | http://yourstories.podbean.com/mf/feed/cjv3ey/ProducersPicks.mp3                              |      |              |
    | The Your Stories Christmas Special Starring Jon Lester                                              | 2012-12-23     | Your Stories                          | http://yourstories.podbean.com/mf/feed/nv48yz/Christmas.mp3                                   |      |              |
    | The Nerd Wars Holiday Special: Episode I                                                            | 2012-12-18     | Your Stories                          | http://yourstories.podbean.com/mf/feed/gnchyc/NerdWaroftheWorld.mp3                           |      |              |
    | Alex Talavera Talks About Surviving Three Incidents with Armed Attackers                            | 2012-12-17     | Your Stories                          | http://yourstories.podbean.com/mf/feed/e424a2/AlexGuns.mp3                                    |      |              |
    | December 2012 Part 2: It’s the End of the Year as We Know It                                        | 2012-12-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/p9mdgv/December2012Part2.mp3                           |      |              |
    | December 2012 Part 1: Happy Birthday, Dear Nerdologues                                              | 2012-12-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/fkqqer/December2012Part1.mp3                           |      |              |
    | Help Us Pick the Best Of Year 1!                                                                    | 2012-11-15     | Your Stories                          |                                                                                               |      |              |
    | November 2012 Part 2: Champions                                                                     | 2012-11-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/ync3ys/NovemberPart2.mp3                               |      |              |
    | November 2012 Part 1: The Sporting Life                                                             | 2012-11-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/ff2592/NovemberPart1.mp3                               |      |              |
    | For Immediate Release: The Your Stories Drinking Game                                               | 2012-10-23     | Your Stories                          |                                                                                               |      |              |
    | October 2012 Part 2: Sweet Home Suite                                                               | 2012-10-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/v6vnyu/OctoberPart2.mp3                                |      |              |
    | October 2012 Part 1: Home Sweet Home                                                                | 2012-10-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/5mzw8p/OctoberPart1.mp3                                |      |              |
    | September 2012 Part 2: It’s a Thinker                                                               | 2012-09-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/8k2ak/SeptemberPart2.mp3                               |      |              |
    | BONUS Video: Sean Connery Loves Memes                                                               | 2012-09-08     | Your Stories                          |                                                                                               |      |              |
    | September 2012 Part 1: It’s Just a Theory                                                           | 2012-09-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/6zbmx4/SeptemberPart1.mp3                              |      |              |
    | August 2012 BONUS: Armageddon Pie with Cor Res Theater                                              | 2012-08-22     | Your Stories                          | http://yourstories.podbean.com/mf/feed/tajair/CorRes.mp3                                      |      |              |
    | August 2012 Part 2: Land of Confusion                                                               | 2012-08-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/ktuhki/AugustPart2.mp3                                 |      |              |
    | August 2012 Part 1: It’s The End of the World as We Know It                                         | 2012-08-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/3icndu/AugustPart1.mp3                                 |      |              |
    | July 2012 Part 2: Fight For Your Right                                                              | 2012-07-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/4v4ev6/Julypart2.mp3                                   |      |              |
    | July 2012 Part 1: Friends in Low Places                                                             | 2012-07-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/hsd2ye/Julypart1.mp3                                   |      |              |
    | BONUS: Live at Project Comic-Con, St. Louis                                                         | 2012-06-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/tx4dd/StLouis.mp3                                      |      |              |
    | June 2012: Family Matters                                                                           | 2012-06-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/7926ih/June.mp3                                        |      |              |
    | May 2012 Part 2: Like Triple X, But With Less Vin Diesel                                            | 2012-05-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/u7vk52/Maypart2.mp3                                    |      |              |
    | May 2012 Part 1: Let’s Talk About Sex                                                               | 2012-05-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/6mgb9n/Maypart1.mp3                                    |      |              |
    | May Preview featuring the Fantastic Four!                                                           | 2012-04-24     | Your Stories                          | http://yourstories.podbean.com/mf/feed/t54vt/Marcpreview.mp3                                  |      |              |
    | April 2012 Part 2: Krazy Kustomers and Kool Kids                                                    | 2012-04-16     | Your Stories                          | http://yourstories.podbean.com/mf/feed/ne8akp/April2.mp3                                      |      |              |
    | Check out Dwight and Eric on the Unshaven Rant-Cast!                                                | 2012-04-10     | Your Stories                          |                                                                                               |      |              |
    | April 2012 Part 1: Teach Your Children Well, Etc.                                                   | 2012-04-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/z6sfiq/AprilPart1.mp3                                  |      |              |
    | BONUS Episode: Live at Challengers Comics!                                                          | 2012-03-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/z4kpj/Challengers.mp3                                  |      |              |
    | March 2012 - The Music of Our Nerdy Hearts                                                          | 2012-03-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/cyir2w/March.mp3                                       |      |              |
    | February 2012 Part 2                                                                                | 2012-02-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/rzyu39/FebruaryPart2.mp3                               |      |              |
    | February 2012 Part 1                                                                                | 2012-02-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/nkk2in/FebruaryPart1.mp3                               |      |              |
    | NEW VENUE: The Upstairs Gallery                                                                     | 2012-01-06     | Your Stories                          |                                                                                               |      |              |
    | VIDEO: Girl in a Comic Book Shop                                                                    | 2012-01-04     | Your Stories                          |                                                                                               |      |              |
    | January 2012                                                                                        | 2012-01-01     | Your Stories                          | http://yourstories.podbean.com/mf/feed/qksrjs/January.mp3                                     |      |              |
    | December 2011 Part 2                                                                                | 2011-12-15     | Your Stories                          | http://yourstories.podbean.com/mf/feed/4wssix/Decemberpart2.mp3                               |      |              |
    | December 2011 Part 1                                                                                | 2011-12-10     | Your Stories                          | http://yourstories.podbean.com/mf/feed/n9n49h/Decemberpart1.mp3                               |      |              |
    | Help us make a year-end compilation!                                                                | 2013-11-25     | Your Stories                          |                                                                                               |      |              |
    | November 2013: Other Options, Part 2                                                                | 2013-11-25     | Your Stories                          | http://yourstories.podbean.com/mf/feed/wgj4d/November2013Part2.mp3                            |      |              |
    | November 2013: Other Options, Part 1                                                                | 2013-11-11     | Your Stories                          | http://yourstories.podbean.com/mf/feed/hzq5jt/November2013Part1.mp3                           |      |              |
    | Episode 25 - MBSing with Mary Zee - Buffy the Vampire Slayer                                        | 2013-11-27     | MBSing                                | http://mbsing.podbean.com/mf/feed/pi6tq4/MBSingwithMaryZee.mp3                                |      |              |
    | Episode 24 - MBSing with Jeremy Kanne - Self-Teaching                                               | 2013-11-20     | MBSing                                | http://mbsing.podbean.com/mf/feed/vdihzr/MBSingwithJeremyKanne.mp3                            |      |              |
    | Episode 23 - MBSing with Alex Trepka - Pro Wrestling                                                | 2013-11-13     | MBSing                                | http://mbsing.podbean.com/mf/feed/bgeqac/MBSingwithAlexTrepka.mp3                             |      |              |
    | Episode 22 - MBSing with Daniel Duval - Bowling                                                     | 2013-11-06     | MBSing                                | http://mbsing.podbean.com/mf/feed/5igtpu/MBSingwithDanielDuval.mp3                            |      |              |
    | Episode 21 - MBSing with Jimmy Pennington - The Great American Novel                                | 2013-10-30     | MBSing                                | http://mbsing.podbean.com/mf/feed/bsaznr/MBSingwithJimmyPennington.mp3                        |      |              |
    | Episode 20 - MBSing with Bret Dorman - Godzilla                                                     | 2013-10-23     | MBSing                                | http://mbsing.podbean.com/mf/feed/ab8gbx/MBSingwithBretDorman.mp3                             |      |              |
    | Episode 19 - MBSing with Chandler Goodman and Spencer Smith - College Football                      | 2013-10-16     | MBSing                                | http://mbsing.podbean.com/mf/feed/y29v75/MBSingwithChandlerGoodmanandSpencerSmith.mp3         |      |              |
    | Episode 18 - MBSing with James Allen - Rap                                                          | 2013-10-09     | MBSing                                | http://mbsing.podbean.com/mf/feed/442nms/MBSingwithJamesAllen.mp3                             |      |              |
    | Episode 17 - MBSing with Jennifer Baird - Dyslexia                                                  | 2013-10-02     | MBSing                                | http://mbsing.podbean.com/mf/feed/jn7ri/MBSingwithJenniferBaird.mp3                           |      |              |
    | Episode 16 - MBSing with Kellen Terrett - Coffee                                                    | 2013-09-25     | MBSing                                | http://mbsing.podbean.com/mf/feed/f3hc28/MBSingwithKellenTerrett.mp3                          |      |              |
    | Episode 15 - MBSing with Jessie Stegner - Musicals                                                  | 2013-09-18     | MBSing                                | http://mbsing.podbean.com/mf/feed/dc8dgv/MBSingwithJessieStegner.mp3                          |      |              |
    | Episode 14 - MBSing with Bill Meincke - MLB                                                         | 2013-09-11     | MBSing                                | http://mbsing.podbean.com/mf/feed/h39itj/MBSingwithBillMeincke.mp3                            |      |              |
    | Episode 13 - MBSing with Eric Garneau - Bruce Springsteen                                           | 2013-09-04     | MBSing                                | http://mbsing.podbean.com/mf/feed/3eamv/MBSingwithEricGarneau.mp3                             |      |              |
    | Episode 12 - MBSing with Alex Talavera - Anthony Bourdain: No Reservations                          | 2013-08-28     | MBSing                                | http://mbsing.podbean.com/mf/feed/uz4kr3/MBSingwithAlexTalavera.mp3                           |      |              |
    | Episode 11 - MBSing with Stephanie Weber - Playwriting                                              | 2013-08-19     | MBSing                                | http://mbsing.podbean.com/mf/feed/ixw7ua/MBSingwithStephanieWeber.mp3                         |      |              |
    | Episode 10 - MBSing with Lauren Oprah Walker - Veronica Mars                                        | 2013-08-10     | MBSing                                | http://mbsing.podbean.com/mf/feed/amh7c/MBSingwithLaurenOprahWalker.mp3                       |      |              |
