<?php

/**
 * @file
 * Contains views_rss_podcast.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function views_rss_podcast_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the views_rss_podcast module.
    case 'help.page.views_rss_podcast':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Extends Views RSS capability to use itunes fields') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function views_rss_podcast_theme() {
  return [
    'views_rss_podcast_row' => [
      'render element' => 'children',
    ],
  ];
}


/**
 * Prepares variables for views RSS item templates.
 *
 * Default template: views-view-row-podcast-rss.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - row: The raw results rows.
 */
function template_preprocess_views_view_row_podcast_rss(&$variables) {
  template_preprocess_views_view_row_rss($variables);
}
