<?php

/**
 * @file
 * Contains nerdcustom.module..
 */

use \Drupal\node\NodeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_node_links_alter().
 */
function nerdcustom_node_links_alter(array &$links, NodeInterface $entity, array &$context) {

  if ($entity->bundle() === 'person') {
    $links['node']['#links']['node-readmore'] = array(
      'title' => t('Full bio, podcast clips and links<span class="visually-hidden"> for @title</span>', array(
        '@title' => $node_title_stripped,
      )),
      'url' => $entity->urlInfo(),
      'language' => $entity->language(),
      'attributes' => array(
        'rel' => 'tag',
        'title' => $node_title_stripped,
      ),
    );
  }
  else {

    if (!empty($links['node']['#links']['node-readmore'])) {
      unset ($links['node']['#links']['node-readmore']);
    }
  }
}

/**
 * Implements hook_entity_insert().
 */
function nerdcustom_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity instanceof NodeInterface) {
    \Drupal::service('nerdcustom.clipcreator')->createClips($entity);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function nerdcustom_canonical_helper(&$variables, $node) {

  foreach ($node->uriRelationships() as $rel) {
    $url = $node->toUrl($rel);
    // Add link relationships if the user is authenticated or if the anonymous
    // user has access. Access checking must be done for anonymous users to
    // avoid traffic to inaccessible pages from web crawlers. For
    // authenticated users, showing the links in HTML head does not impact
    // user experience or security, since the routes are access checked when
    // visited and only visible via view source. This prevents doing
    // potentially expensive and hard to cache access checks on every request.
    // This means that the page will vary by user.permissions. We also rely on
    // the access checking fallback to ensure the correct cacheability
    // metadata if we have to check access.
    if ($variables['user']->isAuthenticated() || $url->access($variables['user'])) {
      // Set the node path as the canonical URL to prevent duplicate content.
      $variables['#attached']['html_head_link'][] = array(
        array(
          'rel' => $rel,
          'href' => $url->toString(),
        ),
        TRUE,
      );
    }

    if ($rel == 'canonical') {
      // Set the non-aliased canonical path as a default shortlink.
      $variables['#attached']['html_head_link'][] = array(
        array(
          'rel' => 'shortlink',
          'href' => $url->setOption('alias', TRUE)->toString(),
        ),
        TRUE,
      );
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function nerdcustom_preprocess_ds_entity_view(&$variables) {

  if ($variables['content']['#view_mode'] === 'full' && $variables['content']['#entity_type'] === 'node') {
    $node = $variables['content']['#' . $variables['content']['#entity_type']];
    nerdcustom_canonical_helper($variables, $node);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function nerdcustom_preprocess_node(&$variables) {
  if ($variables['view_mode'] === 'full') {
    nerdcustom_canonical_helper($variables, $variables['node']);
  }
}
