Feature: Clip

  @api
  Scenario: Clip
    Given I am logged in as a user with the "administrator" role
    When I visit "admin/content-migration/clip?field_date_published_value="
    Then I should see the following table portion
   


    
      | Title                                                                      | Podcast      | Authors                                                                                                              | End Time | Start Time | episode                                                  | Date Published |
      | Caitlin Costello: The Comforts of Home                                     | Your Stories | Caitlin Costello                                                                                                     | 2784     | 1722       | December 2011 Part 1                                     |                |
      | Claire Friedman: Growing Up                                                | Your Stories | Claire Friedman                                                                                                      | 1157     | 825        | December 2011 Part 1                                     |                |
      | Dwight & Eric: Crazy/Rolling in the Deep                                   | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 2962     | 2784       | December 2011 Part 1                                     |                |
      | Dwight & Eric: Runaround                                                   | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 500      | 262        | December 2011 Part 1                                     |                |
      | Dwight & Eric: Teenage Dirtbag                                             | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 261      | 72         | December 2011 Part 1                                     |                |
      | Mary Zee: Jesus Camp                                                       | Your Stories | Mary Zee                                                                                                             | 1717     | 1158       | December 2011 Part 1                                     |                |
      | Steve Persch: When Bad Lyrics Get Serious                                  | Your Stories | Steve Persch                                                                                                         | 824      | 500        | December 2011 Part 1                                     |                |
      | The Nerdologues: Prison Break pilot reenactment                            | Your Stories | Kevin Reader, Chris Geiger, Caitlin Costello, Bill Kenkel, Alex Talavera, Matt Kawa, Aaron Pinkston, John Thibodeaux | 2784     | 1895       | December 2011 Part 1                                     |                |
      | Aaron Pinkston: My Film Disease                                            | Your Stories | Aaron Pinkston                                                                                                       | 2682     | 1820       | December 2011 Part 2                                     |                |
      | Angela: Letters to the Editor                                              | Your Stories | Angela                                                                                                               | 1820     | 1308       | December 2011 Part 2                                     |                |
      | Dwight & Eric: El Scorcho                                                  | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 272      | 56         | December 2011 Part 2                                     |                |
      | Dwight & Eric: Sledgehammer                                                | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 2905     | 2683       | December 2011 Part 2                                     |                |
      | Eric Garneau: Of Comic Books & Broken Hearts                               | Your Stories | Eric Garneau                                                                                                         | 635      | 273        | December 2011 Part 2                                     |                |
      | Jeremy Kanne: Le Lapin Will Happen                                         | Your Stories | Jeremy Kanne                                                                                                         | 1307     | 636        | December 2011 Part 2                                     |                |
      | Alex Talavera: Crisis on Infinite Alexes                                   | Your Stories | Alex Talavera                                                                                                        | 2380     | 1908       | January 2012                                             |                |
      | Andrew Bentley: Love Letter to Iron Maiden                                 | Your Stories | Andrew Bentley                                                                                                       | 1907     | 1317       | January 2012                                             |                |
      | Dwight & Eric: 1979                                                        | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 360      | 96         | January 2012                                             |                |
      | Dwight & Eric: Because the Night                                           | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 2936     | 2734       | January 2012                                             |                |
      | Dwight & Eric: Brian Wilson                                                | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 601      | 360        | January 2012                                             |                |
      | Eric Garneau: Born to Monologue                                            | Your Stories | Eric Garneau                                                                                                         | 2733     | 2380       | January 2012                                             |                |
      | Eric: Wicker Man (partial)                                                 | Your Stories | Eric Garneau                                                                                                         | 0        | 0          | January 2012                                             |                |
      | Shawn Boyle: Proving the Preciousness of Life with Math                    | Your Stories | Shawn Patrick Boyle                                                                                                  | 1316     | 994        | January 2012                                             |                |
      | Kevin Reader: Basketball Diaries                                           | Your Stories | Kevin Reader                                                                                                         | 1612     | 1169       | February 2012 Part 1                                     |                |
      | Mat Elfring: Living the Life at Comic Vine                                 | Your Stories | Mat Elfring                                                                                                          | 2182     | 1612       | February 2012 Part 1                                     |                |
      | Matt Heckler: Bottomed Out                                                 | Your Stories | Matt Heckler                                                                                                         | 2411     | 2182       | February 2012 Part 1                                     |                |
      | Matt Heckler: Future War                                                   | Your Stories | Matt Heckler                                                                                                         | 410      | 177        | February 2012 Part 1                                     |                |
      | Shawn Boyle: A Glass Half Full, and Full of Poison                         | Your Stories | Shawn Patrick Boyle                                                                                                  | 1169     | 775        | February 2012 Part 1                                     |                |
      | Steve Persch: Coolness in Context                                          | Your Stories | Steve Persch                                                                                                         | 775      | 410        | February 2012 Part 1                                     |                |
      | Aaron Pinkston: An Oral History of Haircuts                                | Your Stories | Aaron Pinkston                                                                                                       | 1654     | 842        | February 2012 Part 2                                     |                |
      | Bill Kenkel: The Futility of Existence                                     | Your Stories | Bill Kenkel                                                                                                          | 842      | 587        | February 2012 Part 2                                     |                |
      | Byron Hatfield: Bad, Bad Summer Jobs                                       | Your Stories | Byron Hatfield                                                                                                       | 2152     | 1654       | February 2012 Part 2                                     |                |
      | Matt Heckler: A Dying Man                                                  | Your Stories | Matt Heckler                                                                                                         | 587      | 331        | February 2012 Part 2                                     |                |
      | Matt Heckler: Julia                                                        | Your Stories | Matt Heckler                                                                                                         | 331      | 152        | February 2012 Part 2                                     |                |
      | Matt Heckler: The Waitress & The Derelict                                  | Your Stories | Matt Heckler                                                                                                         | 2503     | 2152       | February 2012 Part 2                                     |                |
      | Andrew Bentley: Metal Lightning, Autopsy of My Soul, Forbidden Fruit       | Your Stories | Andrew Bentley                                                                                                       | 1336     | 583        | March 2012 - The Music of Our Nerdy Hearts               |                |
      | Bill Kenkel: Part of That World                                            | Your Stories | Bill Kenkel                                                                                                          | 2109     | 1792       | March 2012 - The Music of Our Nerdy Hearts               |                |
      | Claire Friedman: High School Xanga Adventures                              | Your Stories | Claire Friedman                                                                                                      | 1792     | 1336       | March 2012 - The Music of Our Nerdy Hearts               |                |
      | Claire Friedman: The Dirty Internet Song                                   | Your Stories | Claire Friedman                                                                                                      | 3640     | 3435       | March 2012 - The Music of Our Nerdy Hearts               |                |
      | Dwight & Eric: Moral Fiber                                                 | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 582      | 423        | March 2012 - The Music of Our Nerdy Hearts               |                |
      | Dwight & Eric: The Enemy Song                                              | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 423      | 128        | March 2012 - The Music of Our Nerdy Hearts               |                |
      | Dwight & Eric: The World is Falling                                        | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 4103     | 3890       | March 2012 - The Music of Our Nerdy Hearts               |                |
      | Eric Garneau: On Writing for Teens                                         | Your Stories | Eric Garneau                                                                                                         | 2385     | 2128       | March 2012 - The Music of Our Nerdy Hearts               |                |
      | Eric: Here Comes the Morning                                               | Your Stories | Eric Garneau                                                                                                         | 3890     | 3658       | March 2012 - The Music of Our Nerdy Hearts               |                |
      | Myke Golliday: Close Encounters of the Turtle Kind                         | Your Stories | Myke Golliday                                                                                                        | 3101     | 2895       | March 2012 - The Music of Our Nerdy Hearts               |                |
      | Shawn Boyle: The Power of Music                                            | Your Stories | Shawn Patrick Boyle                                                                                                  | 2895     | 2385       | March 2012 - The Music of Our Nerdy Hearts               |                |
      | Andrew Bentley: A Grievance with Identity Crisis                           | Your Stories | Andrew Bentley                                                                                                       | 1190     | 870        | BONUS Episode: Live at Challengers Comics!               |                |
      | Claire & Eric: Challengers                                                 | Your Stories | Claire Friedman, Eric Garneau                                                                                        | 1883     | 1671       | BONUS Episode: Live at Challengers Comics!               |                |
      | Claire Friedman: Growing Up with Batman                                    | Your Stories | Claire Friedman                                                                                                      | 842      | 556        | BONUS Episode: Live at Challengers Comics!               |                |
      | DeAndre McNeal: Spider-Man in the Flesh                                    | Your Stories | DeAndre McNeal                                                                                                       | 2670     | 2232       | BONUS Episode: Live at Challengers Comics!               |                |
      | Dwight & Eric: I Believe I Can Fly                                         | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 3441     | 3180       | BONUS Episode: Live at Challengers Comics!               |                |
      | Dwight & Eric: I Just Had Sex                                              | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 338      | 173        | BONUS Episode: Live at Challengers Comics!               |                |
      | Ed Soderberg: Battle Wounds for DS9                                        | Your Stories | Ed Soderberg                                                                                                         | 2232     | 1884       | BONUS Episode: Live at Challengers Comics!               |                |
      | Nerdologues: Awesome Dude Rebuttal                                         | Your Stories | Chris Geiger, Joe Gennaro                                                                                            | 3174     | 2908       | BONUS Episode: Live at Challengers Comics!               |                |
      | Nerdologues: Fantastic Foreplay                                            | Your Stories | Steve Persch, Claire Friedman                                                                                        | 2907     | 2670       | BONUS Episode: Live at Challengers Comics!               |                |
      | Tim Manning: On Meeting Christopher Nolan                                  | Your Stories | Tim Manning                                                                                                          | 1657     | 1191       | BONUS Episode: Live at Challengers Comics!               |                |
      | Claire Friedman: Youth Nerd Culture Today                                  | Your Stories | Claire Friedman                                                                                                      | 743      | 304        | April 2012 Part 1: Teach Your Children Well, Etc.        |                |
      | Dwight & Eric: Breakfast at Tiffany's                                      | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 300      | 108        | April 2012 Part 1: Teach Your Children Well, Etc.        |                |
      | Dwight & Eric: I Want It That Way                                          | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 2658     | 2492       | April 2012 Part 1: Teach Your Children Well, Etc.        |                |
      | Dwight & Eric: The Hook                                                    | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 2492     | 2124       | April 2012 Part 1: Teach Your Children Well, Etc.        |                |
      | Sawyer Heppes: Ferris Bueller in Batman Underwear                          | Your Stories | Sawyer Heppes                                                                                                        | 1120     | 744        | April 2012 Part 1: Teach Your Children Well, Etc.        |                |
      | Steve Persch: Death to America ('s Funniest Home Videos)                   | Your Stories | Steve Persch                                                                                                         | 1388     | 1120       | April 2012 Part 1: Teach Your Children Well, Etc.        |                |
      | Andrew Bentley: Pleasure in Fictional Demise                               | Your Stories | Andrew Bentley                                                                                                       | 583      | 232        | April 2012 Part 2: Krazy Kustomers and Kool Kids         |                |
      | Eric & Dwight: Pinball Wizard                                              | Your Stories | Eric Garneau, Dwight Haesler                                                                                         | 232      | 87         | April 2012 Part 2: Krazy Kustomers and Kool Kids         |                |
      | Eric Garneau: Krazy Kustomers Part 2                                       | Your Stories | Eric Garneau                                                                                                         | 1320     | 851        | April 2012 Part 2: Krazy Kustomers and Kool Kids         |                |
      | Jon Lester: Working With the Cool Kids                                     | Your Stories | Jon Lester                                                                                                           | 1734     | 1320       | April 2012 Part 2: Krazy Kustomers and Kool Kids         |                |
      | Myke Golliday: Krazy Kustomers Part 1                                      | Your Stories | Myke Golliday                                                                                                        | 851      | 583        | April 2012 Part 2: Krazy Kustomers and Kool Kids         |                |
      | Ruchie: Med School is Sexy                                                 | Your Stories | Ruchie                                                                                                               | 1969     | 1734       | April 2012 Part 2: Krazy Kustomers and Kool Kids         |                |
      | Shawn Boyle: Camp Unknown                                                  | Your Stories | Shawn Patrick Boyle                                                                                                  | 2674     | 1970       | April 2012 Part 2: Krazy Kustomers and Kool Kids         |                |
      | Steve: Pabstblueribbonville                                                | Your Stories | Steve Persch                                                                                                         | 2940     | 2675       | April 2012 Part 2: Krazy Kustomers and Kool Kids         |                |
      | Alex Talavera: Shortcomings                                                | Your Stories | Alex Talavera                                                                                                        | 2722     | 2046       | May 2012 Part 1: Let’s Talk About Sex                    |                |
      | Allison MacWilliams-Brooks: Lessons for a Dorky Girl in a Sex-Crazed World | Your Stories | Allison MacWilliams-Brooks                                                                                           | 2034     | 1454       | May 2012 Part 1: Let’s Talk About Sex                    |                |
      | Dwight & Eric: Poker Face                                                  | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 3643     | 3414       | May 2012 Part 1: Let’s Talk About Sex                    |                |
      | Eric Garneau: I Fell in Love With a Stripper                               | Your Stories | Eric Garneau                                                                                                         | 458      | 130        | May 2012 Part 1: Let’s Talk About Sex                    |                |
      | Kevin Reader: My First Lapdance                                            | Your Stories | Kevin Reader                                                                                                         | 800      | 458        | May 2012 Part 1: Let’s Talk About Sex                    |                |
      | Sawyer Heppes: The Princess is in Another Castle                           | Your Stories | Sawyer Heppes                                                                                                        | 1393     | 800        | May 2012 Part 1: Let’s Talk About Sex                    |                |
      | Steve Persch: Watch Out for Those Other Queens                             | Your Stories | Steve Persch                                                                                                         | 3338     | 3040       | May 2012 Part 1: Let’s Talk About Sex                    |                |
      | Andrew Bentley: Selling the Culture of Sex                                 | Your Stories | Andrew Bentley                                                                                                       | 969      | 656        | May 2012 Part 2: Like Triple X, But With Less Vin Diesel |                |
      | Charlie Connell: The Randall of the XXX World                              | Your Stories | Charlie Connell                                                                                                      | 1849     | 1377       | May 2012 Part 2: Like Triple X, But With Less Vin Diesel |                |
      | Dwight & Eric: Fuck Her Gently                                             | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 655      | 490        | May 2012 Part 2: Like Triple X, But With Less Vin Diesel |                |
      | Dwight & Eric: Ignition                                                    | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 3546     | 3334       | May 2012 Part 2: Like Triple X, But With Less Vin Diesel |                |
      | Dwight & Eric: Marvin Gaye medley                                          | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 489      | 192        | May 2012 Part 2: Like Triple X, But With Less Vin Diesel |                |
      | Ed Soderberg: Like D&D, But Less Sexy                                      | Your Stories | Ed Soderberg                                                                                                         | 1377     | 969        | May 2012 Part 2: Like Triple X, But With Less Vin Diesel |                |
      | Mary Zee: Feeling Naked on Stage (Literally)                               | Your Stories | Mary Zee                                                                                                             | 2334     | 1850       | May 2012 Part 2: Like Triple X, But With Less Vin Diesel |                |
      | Myke Golliday: Dating a Gamer                                              | Your Stories | Myke Golliday                                                                                                        | 2668     | 2454       | May 2012 Part 2: Like Triple X, But With Less Vin Diesel |                |
      | Shawn Boyle: The Horny Trinity, part 3 (parts 1 & 2 can be found here)     | Your Stories | Shawn Patrick Boyle                                                                                                  | 3332     | 2669       | May 2012 Part 2: Like Triple X, But With Less Vin Diesel |                |
      | Tim Manning: Judging Girlfriends Through Star Wars                         | Your Stories | Tim Manning                                                                                                          | 2454     | 2334       | May 2012 Part 2: Like Triple X, But With Less Vin Diesel |                |
      | Andrew Bentley: My Sister                                                  | Your Stories | Andrew Bentley                                                                                                       | 3710     | 3288       | June 2012: Family Matters                                |                |
      | Bill Kenkel: The End of the World                                          | Your Stories | Bill Kenkel                                                                                                          | 1822     | 1526       | June 2012: Family Matters                                |                |
      | Charlie Connell: A Family of Vikings                                       | Your Stories | Charlie Connell                                                                                                      | 3288     | 3045       | June 2012: Family Matters                                |                |
      | Chris Crotwell: The Real-Life 7 Dwarves                                    | Your Stories | Chris Crotwell                                                                                                       | 536      | 194        | June 2012: Family Matters                                |                |
      | Dwight & Eric: Lightning Crashes                                           | Your Stories | Dwight Haesler, Eric Garneau                                                                                         | 4052     | 3710       | June 2012: Family Matters                                |                |
      | Myke Golliday: A Boy and His Frog                                          | Your Stories | Myke Golliday                                                                                                        | 2339     | 1822       | June 2012: Family Matters                                |                |
      | Nora Seidman: A Luke & Leia Thing                                          | Your Stories | Nora Seidman                                                                                                         | 1525     | 1222       | June 2012: Family Matters                                |                |
      | Rebecca: Piano Bar Fun                                                     | Your Stories | Rebecca M                                                                                                            | 3045     | 2783       | June 2012: Family Matters                                |                |
      | Sawyer Heppes: … But I See Your Party Has No Wizard                        | Your Stories | Sawyer Heppes                                                                                                        | 1222     | 537        | June 2012: Family Matters                                |                |
      | Shawn Boyle: Rewriting Family History                                      | Your Stories | Shawn Patrick Boyle                                                                                                  | 4386     | 4053       | June 2012: Family Matters                                |                |
      | Shawn Boyle: The Marijuanalogs                                             | Your Stories | Shawn Patrick Boyle                                                                                                  | 2776     | 2680       | June 2012: Family Matters                                |                |
      | Fred Dukes: Commencement at Xavier's                                       | Your Stories | Chris Geiger                                                                                                         | 1020     | 800        | BONUS: Live at Project Comic-Con, St. Louis              |                |
      | Joe Gennaro: Football + Video Games = ?                                    | Your Stories | Joe Gennaro                                                                                                          | 795      | 552        | BONUS: Live at Project Comic-Con, St. Louis              |                |
     

    When I visit "admin/content-migration/clip"
    Then I should see the following table portion


  
      | Title                                                              | Podcast      | Authors                                       | End Time | Start Time | episode                                                              | Date Published |
      | Kevin Reader: Bad Reviews                                          | Your Stories | Kevin Reader, Alex Talavera                   | 993      | 606        | January 2012                                                         | 2014-02-13     |
      | Dwight & Eric: The Pokémon Theme                                   | Your Stories | Dwight Haesler, Eric Garneau                  | 2772     | 2707       | November 2012 Part 1: The Sporting Life                              | 2014-02-20     |
      | Mary Zee: The Best Present I Ever Gave / She Saved the World a Lot | Your Stories | Mary Zee                                      | 2104     | 1379       | January 2014: Annual 2, Part 1                                       | 2014-02-27     |
      | Steve Persch: Left Behind                                          | Your Stories | Steve Persch                                  | 3435     | 3101       | March 2012 - The Music of Our Nerdy Hearts                           | 2014-03-06     |
      | Dwight, Eric & Claire: Zombie                                      | Your Stories | Dwight Haesler, Eric Garneau, Claire Friedman | 2684     | 2426       | August 2012 Part 2: Land of Confusion                                | 2014-03-14     |
      | Chris Geiger: Why We Need the Man of Steel                         | Your Stories | Chris Geiger                                  | 917      | 563        | July 2013 Bonus: Superman                                            | 2014-04-04     |
      | Katie Johnston-Smith: Titanic                                      | Your Stories | Katie Johnston-Smith                          | 1334     | 1151       | September 2014 Bonus: Under the Sea Live from the Jangleheart Circus | 2015-01-26     |
      | Claire, Dwight, & Eric: Rebel Yell                                 | Your Stories | Eric Garneau, Claire Friedman, Dwight Haesler | 467      | 162        | November 2013: Other Options, Part 2                                 | 2015-02-09     |
      | Joe Gennaro: 9-to-5er                                              | Your Stories | Joe Gennaro                                   | 1216     | 760        | November 2013: Other Options, Part 1                                 | 2015-02-17     |
      | Mary Beth Smith: This Year                                         | Your Stories | Mary Beth Smith                               | 1076     | 735        | January 2014: Annual 2, Part 2                                       | 2015-03-03     |
      | Chris Geiger: Ode to Will Riker                                    | Your Stories | Chris Geiger                                  | 1060     | 621        | February 2014: Full Hearts, Part 1                                   | 2015-03-10     |
      | Chris Crotwell: Discovering an Author                              | Your Stories | Chris Crotwell                                | 2411     | 1987       | February 2013 Part 1: A New Hope                                     | 2015-03-17     |
      | Bill Kenkel: On Sexuality and Productivity                         | Your Stories | Bill Kenkel                                   | 3040     | 2723       | May 2012 Part 1: Let’s Talk About Sex                                | 2015-03-24     |
      | Cover Stories: Alone                                               | Your Stories | Claire Friedman, Dwight Haesler, Eric Garneau | 620      | 382        | February 2014: Full Hearts, Part 1                                   | 2015-03-31     |
      | Chris Geiger: Gotta Catch ‘Em All                                  | Your Stories | Chris Geiger                                  | 2707     | 2326       | November 2012 Part 1: The Sporting Life                              | 2015-04-13     |
      | Mary Beth Smith: Flight                                            | Your Stories | Mary Beth Smith                               | 602      | 371        | April 2014: Scarred, Part 1                                          | 2015-04-28     |
      | Mary Beth Smith: Helping                                           | Your Stories | Mary Beth Smith                               | 757      | 362        | December 2013: Across the Universe, Part 2                           | 2015-05-26     |
      | Kevin Reader & Chris Geiger: Dungeons & Dragons slam poetry        | Your Stories | Kevin Reader, Chris Geiger                    | 1148     | 1018       | BONUS: Live at Project Comic-Con, St. Louis                          | 2015-06-02     |
      | Katie Johnston-Smith: Mad                                          | Your Stories | Katie Johnston-Smith                          | 3174     | 2968       | May 2015: Press Start, Part 1                                        | 2015-06-23     |
      | Allison MacWilliams-Brooks: My Dad & Star Trek                     | Your Stories | Allison MacWilliams-Brooks                    | 800      | 352        | June 2013: Journey, Part 2                                           | 2015-07-28     |
      | Nerdologues: Magneto Was Right                                     | Your Stories | Bill Kenkel, Steve Persch                     | 560      | 341        | BONUS Episode: Live at Challengers Comics!                           | 2015-08-04     |
      | Dwight & Eric: Land of Confusion                                   | Your Stories | Dwight Haesler, Eric Garneau                  | 521      | 240        | August 2012 Part 2: Land of Confusion                                | 2015-08-18     |
      | Eric Garneau: Call to Adventure                                    | Your Stories | Eric Garneau                                  | 2380     | 2222       | June 2013: Journey, Part 2                                           | 2015-08-25     |
      | Andrew Bentley: Role Models                                        | Your Stories | Andrew Bentley                                | 1033     | 695        | November 2012 Part 1: The Sporting Life                              | 2015-09-01     |
      
