Feature: Clip

  @api
  Scenario: Clip
    Given I am logged in as a user with the "administrator" role
    When I visit "admin/content-migration/clip?order=field_date_published&sort=desc"
    Then I should see the following table portion
| Title                                                                                                                                     | Podcast      | Authors                                                     | End Time | Start Time | episode                                                                            | Date Published Sort ascending |
| Andrew Bentley: Role Models                                                                                                               | Your Stories | Andrew Bentley                                              | 1033     | 695        | November 2012 Part 1: The Sporting Life                                            | 2015-09-01                    |
| Eric Garneau: Call to Adventure                                                                                                           | Your Stories | Eric Garneau                                                | 2380     | 2222       | June 2013: Journey, Part 2                                                         | 2015-08-25                    |
| Dwight & Eric: Land of Confusion                                                                                                          | Your Stories | Dwight Haesler, Eric Garneau                                | 521      | 240        | August 2012 Part 2: Land of Confusion                                              | 2015-08-18                    |
| Nerdologues: Magneto Was Right                                                                                                            | Your Stories | Bill Kenkel, Steve Persch                                   | 560      | 341        | BONUS Episode: Live at Challengers Comics!                                         | 2015-08-04                    |
| Allison MacWilliams-Brooks: My Dad & Star Trek                                                                                            | Your Stories | Allison MacWilliams-Brooks                                  | 800      | 352        | June 2013: Journey, Part 2                                                         | 2015-07-28                    |
| Katie Johnston-Smith: Mad                                                                                                                 | Your Stories | Katie Johnston-Smith                                        | 3174     | 2968       | May 2015: Press Start, Part 1                                                      | 2015-06-23                    |
| Kevin Reader & Chris Geiger: Dungeons & Dragons slam poetry                                                                               | Your Stories | Kevin Reader, Chris Geiger                                  | 1148     | 1018       | BONUS: Live at Project Comic-Con, St. Louis                                        | 2015-06-02                    |
| Mary Beth Smith: Helping                                                                                                                  | Your Stories | Mary Beth Smith                                             | 757      | 362        | December 2013: Across the Universe, Part 2                                         | 2015-05-26                    |
| Mary Beth Smith: Flight                                                                                                                   | Your Stories | Mary Beth Smith                                             | 602      | 371        | April 2014: Scarred, Part 1                                                        | 2015-04-28                    |
| Chris Geiger: Gotta Catch ‘Em All                                                                                                         | Your Stories | Chris Geiger                                                | 2707     | 2326       | November 2012 Part 1: The Sporting Life                                            | 2015-04-13                    |
| Cover Stories: Alone                                                                                                                      | Your Stories | Claire Friedman, Dwight Haesler, Eric Garneau               | 620      | 382        | February 2014: Full Hearts, Part 1                                                 | 2015-03-31                    |
| Bill Kenkel: On Sexuality and Productivity                                                                                                | Your Stories | Bill Kenkel                                                 | 3040     | 2723       | May 2012 Part 1: Let’s Talk About Sex                                              | 2015-03-24                    |
| Chris Crotwell: Discovering an Author                                                                                                     | Your Stories | Chris Crotwell                                              | 2411     | 1987       | February 2013 Part 1: A New Hope                                                   | 2015-03-17                    |
| Chris Geiger: Ode to Will Riker                                                                                                           | Your Stories | Chris Geiger                                                | 1060     | 621        | February 2014: Full Hearts, Part 1                                                 | 2015-03-10                    |
| Mary Beth Smith: This Year                                                                                                                | Your Stories | Mary Beth Smith                                             | 1076     | 735        | January 2014: Annual 2, Part 2                                                     | 2015-03-03                    |
| Joe Gennaro: 9-to-5er                                                                                                                     | Your Stories | Joe Gennaro                                                 | 1216     | 760        | November 2013: Other Options, Part 1                                               | 2015-02-17                    |
| Claire, Dwight, & Eric: Rebel Yell                                                                                                        | Your Stories | Eric Garneau, Claire Friedman, Dwight Haesler               | 467      | 162        | November 2013: Other Options, Part 2                                               | 2015-02-09                    |
| Katie Johnston-Smith: Titanic                                                                                                             | Your Stories | Katie Johnston-Smith                                        | 1334     | 1151       | September 2014 Bonus: Under the Sea Live from the Jangleheart Circus               | 2015-01-26                    |
| Chris Geiger: Why We Need the Man of Steel                                                                                                | Your Stories | Chris Geiger                                                | 917      | 563        | July 2013 Bonus: Superman                                                          | 2014-04-04                    |
| Dwight, Eric & Claire: Zombie                                                                                                             | Your Stories | Dwight Haesler, Eric Garneau, Claire Friedman               | 2684     | 2426       | August 2012 Part 2: Land of Confusion                                              | 2014-03-14                    |
| Steve Persch: Left Behind                                                                                                                 | Your Stories | Steve Persch                                                | 3435     | 3101       | March 2012 - The Music of Our Nerdy Hearts                                         | 2014-03-06                    |
| Mary Zee: The Best Present I Ever Gave / She Saved the World a Lot                                                                        | Your Stories | Mary Zee                                                    | 2104     | 1379       | January 2014: Annual 2, Part 1                                                     | 2014-02-27                    |
| Dwight & Eric: The Pokémon Theme                                                                                                          | Your Stories | Dwight Haesler, Eric Garneau                                | 2772     | 2707       | November 2012 Part 1: The Sporting Life                                            | 2014-02-20                    |
| Kevin Reader: Bad Reviews                                                                                                                 | Your Stories | Kevin Reader, Alex Talavera                                 | 993      | 606        | January 2012                                                                       | 2014-02-13                    |
| Cover Stories: Poker Face                                                                                                                 | Your Stories | Claire Friedman, Dwight Haesler, Eric Garneau               | 683      | 420        | August 2014: Fingers Crossed, Part 1                                               |                               |
