Feature: Events

  @api
  Scenario: Event nodes
    Given I am logged in as a user with the "administrator" role
    When I visit "admin/content-migration/event"
    Then I should see the following table portion


| Title                                                                                | Content type | Location                              | Link                                                                                             | URI                                                                    |
| SATURDAY / saturday                                                                  | Event        | iO Chicago (Wrigleyville)             | Facebook Pagehttps://www.facebook.com/Saturdayx2                                                 | public://io - sphere theater.png                                       |
| Superhero Bar Crawl                                                                  | Event        |                                       | Facebook Eventhttps://www.facebook.com/events/342535039165471/                                   | public://field_image/page/195791_342535039165471_2027587031_n.jpeg     |
| The Skywalking Dead                                                                  | Event        | The Playground Theater                | Facebook Eventhttps://www.facebook.com/events/235727419876858/                                   | public://field_image/page/Nerdologues_Cover_SkywalkingDead-cropped.jpg |
| Your Stories: Coming Home                                                            | Event        | Upstairs Gallery                      | Facebook Eventhttps://www.facebook.com/events/353845161356443/                                   | public://tmnt-your-stories-cropped.jpeg                                |
| Werewolf (Game Night)                                                                | Event        | Fizz Bar / Pub Theater                | Facebook Eventhttps://www.facebook.com/events/403336006388156/                                   |                                                                        |
| New York Comic Con                                                                   | Event        | Javits Center                         | New York Comic Conhttp://www.newyorkcomiccon.com/Whos-Coming/Guests/Ent-Guests/                  | public://nycc-logo-2012-hi.jpg                                         |
| Your Stories: End of the World                                                       | Event        | Upstairs Gallery                      | Facebook Eventhttps://www.facebook.com/events/315442888548303/                                   |                                                                        |
| Your Stories: Propose a Theory                                                       | Event        | Upstairs Gallery                      | Facebook Eventhttps://www.facebook.com/events/390347737680742/                                   |                                                                        |
| Your Stories: Sport                                                                  | Event        | Upstairs Gallery                      | Facebook eventhttps://www.facebook.com/events/104772313010684/                                   | public://tmnt-your-stories-cropped.jpeg                                |
| New York City Sketch Festival                                                        | Event        | The PIT                               | New York City Sketch Festival websitehttp://pitsketchfest.com/schedule/                          | public://Nerdologues_NewYork_facebook.png                              |
| The Nerdologues Present                                                              | Event        | iO Chicago (Wrigleyville)             | Facebook Eventhttps://www.facebook.com/events/401107536621935/                                   | public://Nerdologues_iO.jpg                                            |
| Kokomocon                                                                            | Event        |                                       | Facebook Eventhttps://www.facebook.com/events/263118097124466/                                   |                                                                        |
| Halloween at the PLAYGROUND                                                          | Event        | The Playground Theater                | Facebookhttps://www.facebook.com/events/347453482012081/                                         |                                                                        |
| Poe: Improvised Tales of the Macabre                                                 | Event        | The Playground Theater                | Facebook Eventhttps://www.facebook.com/events/345027628924591/                                   | public://372893_345027628924591_241500805_n.jpeg                       |
| The Nerdologues Present: November Edition                                            | Event        | iO Chicago (Wrigleyville)             | Facebook Eventhttps://www.facebook.com/events/485770601454999/                                   | public://Nerdologues_iO.jpg                                            |
| Your Stories - November: Annual                                                      | Event        | Upstairs Gallery                      | Facebook Eventhttps://www.facebook.com/events/399340320135053/                                   | public://yourstories-r2d2_0.jpg                                        |
| Who Got Glitter on My Controller?                                                    | Event        | Fizz Bar / Pub Theater                | Facebook Eventhttps://www.facebook.com/events/101675663330304                                    | public://Plan9_GlitterOnMyController.jpeg                              |
| The Nerdologues Present: Nerd Wars Holiday Special                                   | Event        | iO Chicago (Wrigleyville)             | Facebook eventhttps://www.facebook.com/events/409740329097282/                                   | public://Nerdologues_NerdWars.jpeg                                     |
| Your Stories - December - Potpourri                                                  | Event        | Upstairs Gallery                      | Facebook eventhttps://www.facebook.com/events/265894080199222/                                   | public://tmnt-your-stories-cropped.jpeg                                |
| The Chicago Sketch Comedy Festival                                                   | Event        |                                       | Facebook eventhttps://www.facebook.com/events/151600438320781/                                   | public://sketch-fest.jpg                                               |
| Your Stories - January - New Beginnings                                              | Event        |                                       | Facebook eventhttps://www.facebook.com/events/757015577771513/                                   | public://tmnt-your-stories-cropped.jpeg                                |
| Nerds Against Humanity                                                               | Event        | iO Chicago (Wrigleyville)             | Facebook Eventhttps://www.facebook.com/events/273767332749702/                                   | public://nerds-against-humanity.jpeg                                   |
| Your Stories - Fan Fiction February                                                  | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/461238063936968/                                   | public://tmnt-your-stories-cropped.jpeg                                |
| Nerds Against Humanity                                                               | Event        |                                       | Facebook eventhttps://www.facebook.com/events/195952787217236/?fref=ts                           | public://nerds_against_humanity.jpg                                    |
| Game Night: Werewolf                                                                 | Event        | The Public House Theatre              | Facebook Eventhttps://www.facebook.com/events/337569613024794/                                   | public://werewolf.jpg                                                  |
| March of Madness                                                                     | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/442413572506112/?ref=22                            |                                                                        |
| March Game Night: Werewolf                                                           | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/163541130464224/                                   | public://werewolf.jpg                                                  |
| Your Stories: March - It's a Mad World                                               | Event        | The Public House Theatre              | Facebook Eventhttps://www.facebook.com/events/544299808937873/                                   |                                                                        |
| Fan Fiction Live!                                                                    | Event        | iO Chicago (Wrigleyville)             | Facebook eventhttps://www.facebook.com/events/123487587834857/                                   |                                                                        |
| We're All Gonna Live Forever                                                         | Event        | The Public House Theatre              | The Public House Theaterhttps://www.facebook.com/events/238650452946276/                         | public://Nerdologues_WAGLF.jpg                                         |
| First Contact Countdown                                                              | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/349128711872264/                                   |                                                                        |
| Your Stories: Crime and Punishment                                                   | Event        | The Public House Theatre              | Facebook Eventhttps://www.facebook.com/events/316512505141096/                                   |                                                                        |
| C2E2 After Party                                                                     | Event        | The Public House Theatre              | Facebook Eventhttps://www.facebook.com/events/440452856046177/?fref=ts                           | public://C2E2-after-party.png                                          |
| C2E2                                                                                 | Event        |                                       | C2E2http://c2e213.mapyourshow.com/5_0/sessions/sessiondetails.cfm?ScheduledSessionI…             | public://C2E2.PNG                                                      |
| Cinco De Bilbo                                                                       | Event        | The Public House Theatre              | Facebook Eventhttps://www.facebook.com/events/461828157229564/                                   | public://cinco-de-bilbo.png                                            |
| The Uncanny Sex-Men & The Rise of The Nude Gods                                      | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/241948655950780/                                   | public://plan-9-uncanny.png                                            |
| Nerd Comedy Festival                                                                 | Event        | Stage 773                             | Facebook eventhttps://www.facebook.com/ChicagoNerdFest                                           | public://ncf.jpg                                                       |
| Your Stories: Journey                                                                | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/570914486274386/                                   | public://yourstories-r2d2.jpg                                          |
| The Dweebutante Ball                                                                 | Event        | The Public House Theatre              | Websitehttp://dweebutanteball.com/                                                               | public://1360656173_swball-white-1.png                                 |
| The Nerdologues Present: JJ Abrams Presents The Nerdologues                          | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/314166438714368/                                   |                                                                        |
| Your Stories - June - Indie                                                          | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/461866150568869/                                   |                                                                        |
| The Nerdologues and Chicago Loot Drop Present: NERDRIFF Superman the Movie           | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/260790460728865/                                   |                                                                        |
| Sayonara Alex Talavera                                                               | Event        | The Public House Theatre              | facebook eventhttps://www.facebook.com/events/556874807704237/                                   | public://sayonara-alex-talavera.jpg                                    |
| Your Stories: Best-Laid Plans                                                        | Event        | The Public House Theatre              | Facebook Eventhttps://www.facebook.com/events/693741390652673/                                   | public://tmnt-your-stories-cropped.jpeg                                |
| Cards Against Humanity Live                                                          | Event        | The Triple Door                       | Ticket Linkhttp://www.thetripledoor.net/Calendar/Events/September-2013/An-Improv-Show.aspx…      | public://cards-against-humanity-live.jpeg                              |
| The Nerdologues Presents: 1993!                                                      | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/167534190102759/                                   |                                                                        |
| Your Stories: September - "1993"                                                     | Event        | The Public House Theatre              | Facebook Eventhttps://www.facebook.com/events/236332636517300/                                   |                                                                        |
| The Nerdologues Presents: Screw These Guys, AMIRITE?!                                | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/203219956523338/                                   | public://Nerdologues_SCREW.jpg                                         |
| The Nerdologues Presents: Your Stories - "Other Options"                             | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/565832170137564/                                   |                                                                        |
| The Nerdologues Presents: Your Stories - Across The Universe (with special guests!)  | Event        | The Public House Theatre              | Pub websitehttps://www.facebook.com/events/407085879418250/                                      | public://safe_image.jpg                                                |
| The Nerdologues Presents: The Multiverse vs. George Lucas                            | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/428741363914793/                                   | public://Nerdologues_multiverse_luc2.jpg                               |
| The Nerdologues Trivia Party! Beat the Nerds (not literally)                         | Event        | The Public House Theatre              | Facebook Eventhttps://www.facebook.com/events/632756003413845/                                   |                                                                        |
| The Nerdologues Presents Your Stories: Annual 2 (with Plan 9 Burlesque!)             | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/633480946716213/                                   |                                                                        |
| The Nerdologuecast Live!                                                             | Event        | The Public House Theatre              | Facebook Eventhttps://www.facebook.com/events/1433308310231434/?source=1                         | public://field_image/podcast/NerdologuecastLogo.jpg                    |
| Your Stories end of year nominations due                                             | Event        |                                       | Facebook detailshttps://www.facebook.com/notes/the-nerdologues/help-us-make-the-your-stories-ye… | public://field_image/podcast/YourStorieslogo.jpg                       |
| The Chicago Sketch Comedy Festival                                                   | Event        | Stage 773                             | Sketch fest schedulehttp://www.chicagosketchfest.com/2014-schedule/                              | public://sketch-fest_0.jpg                                             |
| Holiday Bullshit                                                                     | Event        |                                       | holiday bullshithttps://www.holidaybullshit.com/#dayseven                                        | public://holidaybullshit.jpg                                           |
| Your Stories - Full Hearts                                                           | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/244240355735970/                                   | public://fullhearts.jpg                                                |
| LOL Chicago Comedy Magic Draft                                                       | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/791533474197129/                                   | public://magic_draft.jpg                                               |
| Your Stories - Fan Fiction February 2                                                | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/1397995000459260/                                  | public://tmnt-your-stories-cropped.jpeg                                |
| Chicago Nerd Comedy Festival                                                         | Event        | Stage 773                             | Tumblrhttp://chicagonerdfest.tumblr.com/                                                         | public://nerd-comedy-festival.jpg                                      |
| Nerdologues Game Night: The Leonard Maltin Game!                                     | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/1457304704500118/                                  | public://nerd-game-night.jpg                                           |
| The Nerdologues' Your Stories - SCARRED featuring The Chicago Outfit Roller Derby    | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/1469799633248423/                                  | public://safe_image.jpg                                                |
| Your Stories @ The Chicago Nerd Comedy Fest! - "After Dark"                          | Event        | Stage 773                             | Facebook eventhttps://www.facebook.com/events/772364156108388/                                   | public://safe_image.jpg                                                |
| Your Stories - The Truth (Is Out There)                                              | Event        | The Public House Theatre              | Facebook Eventhttps://www.facebook.com/events/475219189244525/                                   | public://tmnt-your-stories-cropped.jpeg                                |
| Nerdologues Game Night: Superhero Edition!                                           | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/452409861556027/                                   | public://game-night.png                                                |
| May The Fourth: A Star Wars Celebration                                              | Event        | The Public House Theatre              | Eventbritehttps://www.eventbrite.com/e/may-the-fourth-a-star-wars-celebration-tickets-113…       | public://maythefourth.jpg                                              |
| The Lord of the The Wrigley: The Fellowship of The Cubs                              | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/653099028094588/                                   | public://LOW-poster-v4.jpg                                             |
| Your Stories at C2E2                                                                 | Event        |                                       | C2E2http://c2e214.mapyourshow.com/5_0/sessions/sessiondetails.cfm?ScheduledSessionI…             | public://C2E2-Logo-Square.jpg                                          |
| Game Night - "Magic: The Gathering" - Journey Into Nyx                               | Event        | The Public House Theatre              | Pub websitehttp://pubhousetheatre.com/show/nerdologues-game-night/                               | public://GameNight-Special.jpg                                         |
| Your Stories: Fellowship featuring CAKE                                              | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/1432888536961364/                                  | public://safe_image.jpg                                                |
| Your Stories: "Circus" featuring Upstairs Gallery                                    | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/695595797154668/                                   | public://tmnt-your-stories-cropped.jpeg                                |
| A Jangleheart Circus                                                                 | Event        | The Den Theatre                       | Janglehearthttp://www.jangleheartcircus.com/                                                     | public://jangleheart.jpg                                               |
| Your Stories: "Fingers Crossed"                                                      | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/831439803534527/                                   | public://yourstories-r2d2_0.jpg                                        |
| 4 More Years! (A 4 year Anniversary Party)                                           | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/325604634263613/?ref=22                            | public://10540794_763931693649396_4060391992399554639_n.jpg            |
| Your Stories: "Bottoms Up" featuring Geek Bar Chicago!                               | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/431181863688017/                                   | public://geekbar.jpg                                                   |
| Cards Against Humanity Presents: The Doubleclicks and The Nerdologues                | Event        | The Public House Theatre              | http://pubhousetheatre.com/show/dbcksnerd/                                                       | public://doubleclicks.jpg                                              |
| Cards Against Humanity And Friends                                                   | Event        | The Triple Door                       | http://www.thetripledoor.net/Calendar/Events/August-2014/Cards-Against-Humanity…                 | public://CAH.jpg                                                       |
| Your Stories: My Lips Are Sealed featuring Elliott Serrano and Space Happens!        | Event        | The Public House Theatre              | Facebookhttps://www.facebook.com/events/1462439627366873/?ref=6&ref_notif_type=plan_use…         | public://safe_image.jpg                                                |
| Your Stories: "Heartland" featuring Midwest Action AT BLACK ROCK PUB                 | Event        | Black Rock Pub & Kitchen              | Facebook eventhttps://www.facebook.com/events/1519496498288575/?ref=notif&notif_t=plan_user_i…   | public://1010399_10104227107639220_3025468217888620749_n.jpg           |
| Your Stories: APOCALYPSE featuring I Fight Dragons & Our Fair City                   | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/649719925145956/                                   | public://apoc.jpg                                                      |
| Alpha                                                                                | Event        | The Logan Theatre                     | Facebook eventhttps://www.facebook.com/events/731275513613813/?ref=6&ref_notif_type=plan_user…   | public://alpha.png                                                     |
| DRINKS-Giving                                                                        | Event        | The Playground Theater                | Facebook eventhttps://www.facebook.com/events/752328074835793/?ref=6&ref_notif_type=plan_user…   | public://drinksgiving.jpg                                              |
| Your Stories: Annual #3                                                              | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/816962328342728/                                   | public://annual3.jpg                                                   |
| Your Stories @ the Midwinter Gaming Convention!                                      | Event        | Hilton Downtown Milwaukee City Center | Facebook eventhttps://www.facebook.com/events/1669169853309319                                   | public://10624788_842648085777756_3624400720012715564_n.jpg            |
| The 2015 Chicago Sketch Comedy Festival                                              | Event        | Stage 773                             | http://www.chicagosketchfest.com/2015-schedule/                                                  | public://sketch-fest_0.jpg                                             |
| Your Stories: "House Rules" featuring the House Theatre!                             | Event        | The Public House Theatre              | Facebook eventhttps://www.facebook.com/events/386420238196559/                                   | public://10891838_866350543407510_3553860844067715608_n.jpg            |
| Opening for Improvised Star Trek                                                     | Event        | iO Chicago                            | http://ioimprov.com/chicago/io/shows/improvised-star-trek                                        | public://IST_logo.jpg                                                  |
| The Nerdologues take Los Angeles                                                     | Event        | UCB Sunset                            | Ticket Linkhttps://sunset.ucbtheatre.com/performance/36638                                       | public://ucb.jpg                                                       |
| Your Stories: Fanfiction February Three at THREADLESS HQ!                            | Event        | Threadless HQ                         | https://www.facebook.com/events/1042702255746026/                                                | public://f4.jpg                                                        |
| Your Stories: "Pick a Card" with special guests/our new home Cards Against Humanity! | Event        | Some Office                           | Facebook eventhttps://www.facebook.com/events/1646593338903327/                                  | public://nerdologues-poster-giraffe.jpg                                |
| Your Stories: "Press Start" with Arcade Brewery & Other Great Guests!                | Event        | Some Office                           | facebook eventhttps://www.facebook.com/events/1583516601932504/                                  | public://arcade.jpg                                                    |
| CG2 2015 Kick-Off Party                                                              | Event        |                                       | Ticketshttp://www.eventbrite.com/e/cg2-2015-kick-off-party-tickets-16373031177                   | public://1898345_435210509989319_1574741877085689742_o.jpg             |
| MBSing Live: 100th Episode Recording                                                 | Event        | Some Office                           | facebook eventhttps://www.facebook.com/events/465418736941002/                                   | public://1597099_10203931687961317_5774084591933994436_o.jpg           |
| Your Stories: "Sound Idea" with the Chicago Podcast Coop!                            | Event        | Some Office                           | facebook eventhttps://www.facebook.com/events/847866968626260/                                   | public://11212655_928606867181877_8329254593231738963_o.png            |
| The Nerdologues Presents Your Stories Chicago Design Week Edition!                   | Event        | Some Office                           | facebook eventhttps://www.facebook.com/events/1839633619595161/                                  | public://11270245_935219376520626_4363674582254422597_o.jpg            |
| Fisticuffs! Launch Party                                                             | Event        | Some Office                           | Attending linkhttp://attending.io/events/fisticuffs-launch-party                                 | public://fisticuffs-punch-back.png                                     |
| Fisticuffs! Kickstarter - Successfully funded!                                       | Event        |                                       | kickstarterhttps://www.kickstarter.com/projects/nerdologues/fisticuffs                           | public://fisticuffs-punch-back.png                                     |
| High Five Party                                                                      | Event        | Some Office                           | RSVP herehttp://attending.io/events/nerdshighfive                                                | public://highfives.jpg                                                 |
| 'Your Stories' at Adler After Dark!                                                  | Event        | Adler Planetarium                     | Ticket linkhttp://www.adlerplanetarium.org/adler-after-dark#upcomingEvent                        | public://adler-save-pluto.jpg                                          |
| Your Stories: "Fans" with Mark Colomb and Friends!                                   | Event        | Some Office                           | Facebook eventhttps://www.facebook.com/events/1629359290642128/                                  | public://fans.jpg                                                      |
| Your Stories: "Authentic" with Shawn Smith and Friends!                              | Event        | Some Office                           | facebook eventhttps://www.facebook.com/events/1450510378590395/                                  | public://nerdologues-poster-giraffe.jpg                                |
| PAX to the MAX!                                                                      | Event        |                                       |                                                                                                  | public://PAX_qjpreviewth.jpg                                           |
| Chicago Southland Mini Maker Faire                                                   | Event        |                                       | http://southlandmakerfaire.com/                                                                  | public://ChicagoSouthland_MMF_logos_Wordpress1.png                     |
| Fisticuffs! Pickup Party and BONUS Show                                              | Event        | Some Office                           | eventbritehttps://www.eventbrite.com/e/the-nerdologues-present-fisticuffs-pickup-party-an…       | public://field_image/page/Screen Shot 2015-08-28 at 10.39.04 AM.png    |
| Your Stories - "Kids Again" featuring Peaches & Hot Sauce!                           | Event        | Some Office                           | https://www.facebook.com/events/1490584101241502/                                                | public://nerdologues-poster-giraffe.jpg                                |
| The Nerdologues Do Pittsburgh                                                        | Event        | The Arcade Comedy Theatre             | Get tickets!http://arcadecomedytheater.com/events/                                               | public://Pooh.jpg                                                      |
| The Nerdologues Do Pittsburgh                                                        | Event        |                                       | Get tickets!http://arcadecomedytheater.com/events/                                               | public://Pooh.jpg                                                      |
| Your Stories Live - "Horror Stories" featuring the Match 3 Podcast!                  | Event        | Some Office                           | https://www.facebook.com/events/1506013056384134/                                                | public://flanders.jpg                                                  |
| Your Stories -- "A Night with the Stars" featuring Improvised Star Trek!             | Event        | Some Office                           | facebookhttps://www.facebook.com/events/1037672789608584/                                        | public://YourStorieslogo.jpg                                           |
| The Nerd Wars Holiday Special II                                                     | Event        | Some Office                           | facebookhttps://www.facebook.com/events/815669645221669/                                         | public://starwars.jpg                                                  |
| Your Stories: Annual 4                                                               | Event        | Some Office                           | facebookhttps://www.facebook.com/events/1645116112409339/                                        | public://YourStorieslogo.jpg                                           |
| Your Stories: "Character Generation" with the One Shot/Campaign podcasts!            | Event        | Some Office                           | facebook eventhttps://www.facebook.com/events/207641836243282/                                   | public://YourStorieslogo.jpg                                           |
| Your Stories with the Chicago Design Museum                                          | Event        | Chicago Design Museum                 | facebookhttps://www.facebook.com/events/766302493513533/                                         | public://design-museum.jpg                                             |
| Your Stories: Fanfiction 4 featuring the Masters of the Universe                     | Event        | Some Office                           | facebook eventhttps://www.facebook.com/events/1090914514287132/                                  | public://masters-universe.jpg                                          |
| Your Stories: "THanks" w/ Tom Hanks Day (at Begyle Brewing)!                         | Event        | Begyle Brewing                        | https://www.facebook.com/events/166787277036218/                                                 | public://thanks.jpg                                                    |


