Feature: Events

  @api
  Scenario: Event nodes
    Given I am logged in as a user with the "administrator" role
    When I visit "admin/content-migration/event"
    Then I should see the following table portion
    
      | Title                                                                                | Dates                                                                                                     | Content type | Location | Link                                                                                             | URI                                                                    |
      | SATURDAY / saturday                                                                  | 2012-09-08T22:30:00-0500                                                                                  | Event        |          | Facebook Pagehttps://www.facebook.com/Saturdayx2                                                 | public://io - sphere theater.png                                       |
      | Superhero Bar Crawl                                                                  | 2012-08-24T19:00:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/342535039165471/                                   | public://field_image/page/195791_342535039165471_2027587031_n.jpeg     |
      | The Skywalking Dead                                                                  | 2012-07-06T22:00:00-0500 , 2012-07-13T22:00:00-0500 , 2012-07-20T22:00:00-0500 , 2012-07-27T22:00:00-0500 | Event        |          | Facebook Eventhttps://www.facebook.com/events/235727419876858/                                   | public://field_image/page/Nerdologues_Cover_SkywalkingDead-cropped.jpg |
      | Your Stories: Coming Home                                                            | 2012-09-16T19:00:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/353845161356443/                                   | public://tmnt-your-stories-cropped.jpeg                                |
      | Werewolf (Game Night)                                                                | 2012-09-30T18:00:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/403336006388156/                                   |                                                                        |
      | New York Comic Con                                                                   | 2012-10-13T13:30:00-0500                                                                                  | Event        |          | New York Comic Conhttp://www.newyorkcomiccon.com/Whos-Coming/Guests/Ent-Guests/                  | public://nycc-logo-2012-hi.jpg                                         |
      | Your Stories: End of the World                                                       | 2012-07-15T19:00:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/315442888548303/                                   |                                                                        |
      | Your Stories: Propose a Theory                                                       | 2012-08-19T19:00:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/390347737680742/                                   |                                                                        |
      | Your Stories: Sport                                                                  | 2012-10-21T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/104772313010684/                                   | public://tmnt-your-stories-cropped.jpeg                                |
      | New York City Sketch Festival                                                        | 2012-10-11T22:30:00-0500                                                                                  | Event        |          | New York City Sketch Festival websitehttp://pitsketchfest.com/schedule/                          | public://Nerdologues_NewYork_facebook.png                              |
      | The Nerdologues Present                                                              | 2012-10-19T23:59:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/401107536621935/                                   | public://Nerdologues_iO.jpg                                            |
      | Kokomocon                                                                            | 2012-10-20T12:00:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/263118097124466/                                   |                                                                        |
      | Halloween at the PLAYGROUND                                                          | 2012-10-27T23:30:00-0500                                                                                  | Event        |          | Facebookhttps://www.facebook.com/events/347453482012081/                                         |                                                                        |
      | Poe: Improvised Tales of the Macabre                                                 | 2012-10-27T22:00:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/345027628924591/                                   | public://372893_345027628924591_241500805_n.jpeg                       |
      | The Nerdologues Present: November Edition                                            | 2012-11-16T23:59:00-0600                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/485770601454999/                                   | public://Nerdologues_iO.jpg                                            |
      | Your Stories - November: Annual                                                      | 2012-11-18T19:00:00-0600                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/399340320135053/                                   | public://yourstories-r2d2_0.jpg                                        |
      | Who Got Glitter on My Controller?                                                    | 2012-11-08T20:00:00-0600                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/101675663330304                                    | public://Plan9_GlitterOnMyController.jpeg                              |
      | The Nerdologues Present: Nerd Wars Holiday Special                                   | 2012-12-21T23:59:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/409740329097282/                                   | public://Nerdologues_NerdWars.jpeg                                     |
      | Your Stories - December - Potpourri                                                  | 2012-12-16T19:00:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/265894080199222/                                   | public://tmnt-your-stories-cropped.jpeg                                |
      | The Chicago Sketch Comedy Festival                                                   | 2013-01-04T23:00:00-0600 , 2013-01-13T15:00:00-0600                                                       | Event        |          | Facebook eventhttps://www.facebook.com/events/151600438320781/                                   | public://sketch-fest.jpg                                               |
      | Your Stories - January - New Beginnings                                              | 2013-01-20T19:00:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/757015577771513/                                   | public://tmnt-your-stories-cropped.jpeg                                |
      | Nerds Against Humanity                                                               | 2013-01-18T23:59:00-0600                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/273767332749702/                                   | public://nerds-against-humanity.jpeg                                   |
      | Your Stories - Fan Fiction February                                                  | 2013-02-17T20:00:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/461238063936968/                                   | public://tmnt-your-stories-cropped.jpeg                                |
      | Nerds Against Humanity                                                               | 2013-02-15T23:59:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/195952787217236/?fref=ts                           | public://nerds_against_humanity.jpg                                    |
      | Game Night: Werewolf                                                                 | 2013-02-10T19:00:00-0600                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/337569613024794/                                   | public://werewolf.jpg                                                  |
      | March of Madness                                                                     | 2013-03-03T19:00:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/442413572506112/?ref=22                            |                                                                        |
      | March Game Night: Werewolf                                                           | 2013-03-10T17:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/163541130464224/                                   | public://werewolf.jpg                                                  |
      | Your Stories: March - It's a Mad World                                               | 2013-03-17T19:00:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/544299808937873/                                   |                                                                        |
      | Fan Fiction Live!                                                                    | 2013-03-15T23:59:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/123487587834857/                                   |                                                                        |
      | We're All Gonna Live Forever                                                         | 2013-04-07T19:00:00-0500                                                                                  | Event        |          | The Public House Theaterhttps://www.facebook.com/events/238650452946276/                         | public://Nerdologues_WAGLF.jpg                                         |
      | First Contact Countdown                                                              | 2013-04-05T19:30:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/349128711872264/                                   |                                                                        |
      | Your Stories: Crime and Punishment                                                   | 2013-04-21T19:00:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/316512505141096/                                   |                                                                        |
      | C2E2 After Party                                                                     | 2013-04-26T18:00:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/440452856046177/?fref=ts                           | public://C2E2-after-party.png                                          |
      | C2E2                                                                                 | 2013-04-27T16:30:00-0500                                                                                  | Event        |          | C2E2http://c2e213.mapyourshow.com/5_0/sessions/sessiondetails.cfm?ScheduledSessionI…             | public://C2E2.PNG                                                      |
      | Cinco De Bilbo                                                                       | 2013-05-05T19:00:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/461828157229564/                                   | public://cinco-de-bilbo.png                                            |
      | The Uncanny Sex-Men & The Rise of The Nude Gods                                      | 2013-04-28T20:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/241948655950780/                                   | public://plan-9-uncanny.png                                            |
      | Nerd Comedy Festival                                                                 | 2013-06-01T20:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/ChicagoNerdFest                                           | public://ncf.jpg                                                       |
      | Your Stories: Journey                                                                | 2013-05-19T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/570914486274386/                                   | public://yourstories-r2d2.jpg                                          |
      | The Dweebutante Ball                                                                 | 2013-05-12T12:00:00-0500                                                                                  | Event        |          | Websitehttp://dweebutanteball.com/                                                               | public://1360656173_swball-white-1.png                                 |
      | The Nerdologues Present: JJ Abrams Presents The Nerdologues                          | 2013-06-02T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/314166438714368/                                   |                                                                        |
      | Your Stories - June - Indie                                                          | 2013-06-16T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/461866150568869/                                   |                                                                        |
      | The Nerdologues and Chicago Loot Drop Present: NERDRIFF Superman the Movie           | 2013-07-14T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/260790460728865/                                   |                                                                        |
      | Sayonara Alex Talavera                                                               | 2013-08-04T16:00:00-0500                                                                                  | Event        |          | facebook eventhttps://www.facebook.com/events/556874807704237/                                   | public://sayonara-alex-talavera.jpg                                    |
      | Your Stories: Best-Laid Plans                                                        | 2013-08-18T19:00:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/693741390652673/                                   | public://tmnt-your-stories-cropped.jpeg                                |
      | Cards Against Humanity Live                                                          | 2013-09-01T18:30:00-0500                                                                                  | Event        |          | Ticket Linkhttp://www.thetripledoor.net/Calendar/Events/September-2013/An-Improv-Show.aspx…      | public://cards-against-humanity-live.jpeg                              |
      | The Nerdologues Presents: 1993!                                                      | 2013-09-08T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/167534190102759/                                   |                                                                        |
      | Your Stories: September - "1993"                                                     | 2013-09-15T19:00:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/236332636517300/                                   |                                                                        |
      | The Nerdologues Presents: Screw These Guys, AMIRITE?!                                | 2013-10-06T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/203219956523338/                                   | public://Nerdologues_SCREW.jpg                                         |
      | The Nerdologues Presents: Your Stories - "Other Options"                             | 2013-10-20T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/565832170137564/                                   |                                                                        |
      | The Nerdologues Presents: Your Stories - Across The Universe (with special guests!)  | 2013-11-17T19:00:00-0600                                                                                  | Event        |          | Pub websitehttps://www.facebook.com/events/407085879418250/                                      | public://safe_image.jpg                                                |
      | The Nerdologues Presents: The Multiverse vs. George Lucas                            | 2013-11-01T22:00:00-0500 , 2013-11-08T22:00:00-0600 , 2013-11-15T22:00:00-0600 , 2013-11-22T22:00:00-0600 | Event        |          | Facebook eventhttps://www.facebook.com/events/428741363914793/                                   | public://Nerdologues_multiverse_luc2.jpg                               |
      | The Nerdologues Trivia Party! Beat the Nerds (not literally)                         | 2013-11-03T19:00:00-0600                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/632756003413845/                                   |                                                                        |
      | The Nerdologues Presents Your Stories: Annual 2 (with Plan 9 Burlesque!)             | 2013-12-15T18:00:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/633480946716213/                                   |                                                                        |
      | The Nerdologuecast Live!                                                             | 2013-12-01T19:00:00-0600                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/1433308310231434/?source=1                         | public://field_image/podcast/NerdologuecastLogo.jpg                    |
      | Your Stories end of year nominations due                                             | 2013-12-16T23:59:00-0600                                                                                  | Event        |          | Facebook detailshttps://www.facebook.com/notes/the-nerdologues/help-us-make-the-your-stories-ye… | public://field_image/podcast/YourStorieslogo.jpg                       |
      | The Chicago Sketch Comedy Festival                                                   | 2014-01-11T23:00:00-0600                                                                                  | Event        |          | Sketch fest schedulehttp://www.chicagosketchfest.com/2014-schedule/                              | public://sketch-fest_0.jpg                                             |
      | Holiday Bullshit                                                                     | 2013-12-25T23:59:00-0600                                                                                  | Event        |          | holiday bullshithttps://www.holidaybullshit.com/#dayseven                                        | public://holidaybullshit.jpg                                           |
      | Your Stories - Full Hearts                                                           | 2014-01-19T19:00:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/244240355735970/                                   | public://fullhearts.jpg                                                |
      | LOL Chicago Comedy Magic Draft                                                       | 2014-02-09T15:00:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/791533474197129/                                   | public://magic_draft.jpg                                               |
      | Your Stories - Fan Fiction February 2                                                | 2014-02-16T19:00:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/1397995000459260/                                  | public://tmnt-your-stories-cropped.jpeg                                |
      | Chicago Nerd Comedy Festival                                                         | 2014-03-22T22:00:00-0500                                                                                  | Event        |          | Tumblrhttp://chicagonerdfest.tumblr.com/                                                         | public://nerd-comedy-festival.jpg                                      |
      | Nerdologues Game Night: The Leonard Maltin Game!                                     | 2014-03-09T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/1457304704500118/                                  | public://nerd-game-night.jpg                                           |
      | The Nerdologues' Your Stories - SCARRED featuring The Chicago Outfit Roller Derby    | 2014-03-16T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/1469799633248423/                                  | public://safe_image.jpg                                                |
      | Your Stories @ The Chicago Nerd Comedy Fest! - "After Dark"                          | 2014-03-20T23:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/772364156108388/                                   | public://safe_image.jpg                                                |
      | Your Stories - The Truth (Is Out There)                                              | 2014-04-20T19:00:00-0500                                                                                  | Event        |          | Facebook Eventhttps://www.facebook.com/events/475219189244525/                                   | public://tmnt-your-stories-cropped.jpeg                                |
      | Nerdologues Game Night: Superhero Edition!                                           | 2014-04-13T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/452409861556027/                                   | public://game-night.png                                                |
      | May The Fourth: A Star Wars Celebration                                              | 2014-05-04T11:00:00-0500                                                                                  | Event        |          | Eventbritehttps://www.eventbrite.com/e/may-the-fourth-a-star-wars-celebration-tickets-113…       | public://maythefourth.jpg                                              |
      | The Lord of the The Wrigley: The Fellowship of The Cubs                              | 2014-05-23T20:00:00-0500 , 2014-06-29T14:00:00-0500                                                       | Event        |          | Facebook eventhttps://www.facebook.com/events/653099028094588/                                   | public://LOW-poster-v4.jpg                                             |
      | Your Stories at C2E2                                                                 | 2014-04-25T14:15:00-0500                                                                                  | Event        |          | C2E2http://c2e214.mapyourshow.com/5_0/sessions/sessiondetails.cfm?ScheduledSessionI…             | public://C2E2-Logo-Square.jpg                                          |
      | Game Night - "Magic: The Gathering" - Journey Into Nyx                               | 2014-05-11T15:30:00-0500                                                                                  | Event        |          | Pub websitehttp://pubhousetheatre.com/show/nerdologues-game-night/                               | public://GameNight-Special.jpg                                         |
      | Your Stories: Fellowship featuring CAKE                                              | 2014-05-18T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/1432888536961364/                                  | public://safe_image.jpg                                                |
      | Your Stories: "Circus" featuring Upstairs Gallery                                    | 2014-06-15T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/695595797154668/                                   | public://tmnt-your-stories-cropped.jpeg                                |
      | A Jangleheart Circus                                                                 | 2014-08-23T20:00:00-0500                                                                                  | Event        |          | Janglehearthttp://www.jangleheartcircus.com/                                                     | public://jangleheart.jpg                                               |
      | Your Stories: "Fingers Crossed"                                                      | 2014-07-20T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/831439803534527/                                   | public://yourstories-r2d2_0.jpg                                        |
      | 4 More Years! (A 4 year Anniversary Party)                                           | 2014-07-19T21:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/325604634263613/?ref=22                            | public://10540794_763931693649396_4060391992399554639_n.jpg            |
      | Your Stories: "Bottoms Up" featuring Geek Bar Chicago!                               | 2014-08-17T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/431181863688017/                                   | public://geekbar.jpg                                                   |
      | Cards Against Humanity Presents: The Doubleclicks and The Nerdologues                | 2014-09-25T19:00:00-0500                                                                                  | Event        |          | http://pubhousetheatre.com/show/dbcksnerd/                                                       | public://doubleclicks.jpg                                              |
      | Cards Against Humanity And Friends                                                   | 2014-08-30T20:00:00-0500                                                                                  | Event        |          | http://www.thetripledoor.net/Calendar/Events/August-2014/Cards-Against-Humanity…                 | public://CAH.jpg                                                       |
      | Your Stories: My Lips Are Sealed featuring Elliott Serrano and Space Happens!        | 2014-09-21T19:00:00-0500                                                                                  | Event        |          | Facebookhttps://www.facebook.com/events/1462439627366873/?ref=6&ref_notif_type=plan_use…         | public://safe_image.jpg                                                |
      | Your Stories: "Heartland" featuring Midwest Action AT BLACK ROCK PUB                 | 2014-10-19T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/1519496498288575/?ref=notif&notif_t=plan_user_i…   | public://1010399_10104227107639220_3025468217888620749_n.jpg           |
      | Your Stories: APOCALYPSE featuring I Fight Dragons & Our Fair City                   | 2014-11-16T19:00:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/649719925145956/                                   | public://apoc.jpg                                                      |
      | Alpha                                                                                | 2014-11-13T19:00:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/731275513613813/?ref=6&ref_notif_type=plan_user…   | public://alpha.png                                                     |
      | DRINKS-Giving                                                                        | 2014-11-26T20:00:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/752328074835793/?ref=6&ref_notif_type=plan_user…   | public://drinksgiving.jpg                                              |
      | Your Stories: Annual #3                                                              | 2014-12-07T19:00:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/816962328342728/                                   | public://annual3.jpg                                                   |
      | Your Stories @ the Midwinter Gaming Convention!                                      | 2015-01-16T22:00:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/1669169853309319                                   | public://10624788_842648085777756_3624400720012715564_n.jpg            |
      | The 2015 Chicago Sketch Comedy Festival                                              | 2015-01-10T23:00:00-0600                                                                                  | Event        |          | http://www.chicagosketchfest.com/2015-schedule/                                                  | public://sketch-fest_0.jpg                                             |
      | Your Stories: "House Rules" featuring the House Theatre!                             | 2015-01-18T19:00:00-0600                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/386420238196559/                                   | public://10891838_866350543407510_3553860844067715608_n.jpg            |
      | Opening for Improvised Star Trek                                                     | 2015-01-25T20:30:00-0600                                                                                  | Event        |          | http://ioimprov.com/chicago/io/shows/improvised-star-trek                                        | public://IST_logo.jpg                                                  |
      | The Nerdologues take Los Angeles                                                     | 2015-02-06T22:30:00-0600                                                                                  | Event        |          | Ticket Linkhttps://sunset.ucbtheatre.com/performance/36638                                       | public://ucb.jpg                                                       |
      | Your Stories: Fanfiction February Three at THREADLESS HQ!                            | 2015-02-15T19:00:00-0600                                                                                  | Event        |          | https://www.facebook.com/events/1042702255746026/                                                | public://f4.jpg                                                        |
      | Your Stories: "Pick a Card" with special guests/our new home Cards Against Humanity! | 2015-03-15T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/1646593338903327/                                  | public://nerdologues-poster-giraffe.jpg                                |
      | Your Stories: "Press Start" with Arcade Brewery & Other Great Guests!                | 2015-04-19T19:00:00-0500                                                                                  | Event        |          | facebook eventhttps://www.facebook.com/events/1583516601932504/                                  | public://arcade.jpg                                                    |
      | CG2 2015 Kick-Off Party                                                              | 2015-04-17T19:30:00-0500                                                                                  | Event        |          | Ticketshttp://www.eventbrite.com/e/cg2-2015-kick-off-party-tickets-16373031177                   | public://1898345_435210509989319_1574741877085689742_o.jpg             |
      | MBSing Live: 100th Episode Recording                                                 | 2015-05-03T19:00:00-0500                                                                                  | Event        |          | facebook eventhttps://www.facebook.com/events/465418736941002/                                   | public://1597099_10203931687961317_5774084591933994436_o.jpg           |
      | Your Stories: "Sound Idea" with the Chicago Podcast Coop!                            | 2015-05-17T19:00:00-0500                                                                                  | Event        |          | facebook eventhttps://www.facebook.com/events/847866968626260/                                   | public://11212655_928606867181877_8329254593231738963_o.png            |
      | The Nerdologues Presents Your Stories Chicago Design Week Edition!                   | 2015-06-17T20:00:00-0500                                                                                  | Event        |          | facebook eventhttps://www.facebook.com/events/1839633619595161/                                  | public://11270245_935219376520626_4363674582254422597_o.jpg            |
      | Fisticuffs! Launch Party                                                             | 2015-05-29T20:00:00-0500                                                                                  | Event        |          | Attending linkhttp://attending.io/events/fisticuffs-launch-party                                 | public://fisticuffs-punch-back.png                                     |
      | Fisticuffs! Kickstarter - Successfully funded!                                       | 2015-05-29T10:30:00-0500 , 2015-06-30T10:30:00-0500 , 2015-10-01T12:04:00-0500                            | Event        |          | kickstarterhttps://www.kickstarter.com/projects/nerdologues/fisticuffs                           | public://fisticuffs-punch-back.png                                     |
      | High Five Party                                                                      | 2015-06-26T19:00:00-0500                                                                                  | Event        |          | RSVP herehttp://attending.io/events/nerdshighfive                                                | public://highfives.jpg                                                 |
      | 'Your Stories' at Adler After Dark!                                                  | 2015-07-16T18:30:00-0500                                                                                  | Event        |          | Ticket linkhttp://www.adlerplanetarium.org/adler-after-dark#upcomingEvent                        | public://adler-save-pluto.jpg                                          |
      | Your Stories: "Fans" with Mark Colomb and Friends!                                   | 2015-07-19T19:00:00-0500                                                                                  | Event        |          | Facebook eventhttps://www.facebook.com/events/1629359290642128/                                  | public://fans.jpg                                                      |
      | Your Stories: "Authentic" with Shawn Smith and Friends!                              | 2015-08-16T19:00:00-0500                                                                                  | Event        |          | facebook eventhttps://www.facebook.com/events/1450510378590395/                                  | public://nerdologues-poster-giraffe.jpg                                |
      | PAX to the MAX!                                                                      | 2015-08-28T09:00:00-0500                                                                                  | Event        |          |                                                                                                  | public://PAX_qjpreviewth.jpg                                           |
      | Chicago Southland Mini Maker Faire                                                   | 2015-08-22T10:00:00-0500                                                                                  | Event        |          | http://southlandmakerfaire.com/                                                                  | public://ChicagoSouthland_MMF_logos_Wordpress1.png                     |
      | Fisticuffs! Pickup Party and BONUS Show                                              | 2015-09-18T18:30:00-0500                                                                                  | Event        |          | eventbritehttps://www.eventbrite.com/e/the-nerdologues-present-fisticuffs-pickup-party-an…       | public://field_image/page/Screen Shot 2015-08-28 at 10.39.04 AM.png    |
      | Your Stories - "Kids Again" featuring Peaches & Hot Sauce!                           | 2015-09-20T19:00:00-0500                                                                                  | Event        |          | https://www.facebook.com/events/1490584101241502/                                                | public://nerdologues-poster-giraffe.jpg                                |
      | The Nerdologues Do Pittsburgh                                                        | 2015-11-07T22:00:00-0600                                                                                  | Event        |          | Get tickets!http://arcadecomedytheater.com/events/                                               | public://Pooh.jpg                                                      |
      | The Nerdologues Do Pittsburgh                                                        | 2015-11-07T22:00:00-0600                                                                                  | Event        |          | Get tickets!http://arcadecomedytheater.com/events/                                               | public://Pooh.jpg                                                      |
      | Your Stories Live - "Horror Stories" featuring the Match 3 Podcast!                  | 2015-10-18T19:00:00-0500                                                                                  | Event        |          | https://www.facebook.com/events/1506013056384134/                                                | public://flanders.jpg                                                  |
      | Your Stories -- "A Night with the Stars" featuring Improvised Star Trek!             | 2015-11-15T19:00:00-0600                                                                                  | Event        |          | facebookhttps://www.facebook.com/events/1037672789608584/                                        | public://YourStorieslogo.jpg                                           |
      | The Nerd Wars Holiday Special II                                                     | 2015-12-12T20:00:00-0600                                                                                  | Event        |          | facebookhttps://www.facebook.com/events/815669645221669/                                         | public://starwars.jpg                                                  |
      | Your Stories: Annual 4                                                               | 2015-12-13T19:00:00-0600                                                                                  | Event        |          | facebookhttps://www.facebook.com/events/1645116112409339/                                        | public://YourStorieslogo.jpg                                           |
      | Your Stories: "Character Generation" with the One Shot/Campaign podcasts!            | 2016-01-17T19:00:00-0600                                                                                  | Event        |          | facebook eventhttps://www.facebook.com/events/207641836243282/                                   | public://YourStorieslogo.jpg                                           |
      | Your Stories with the Chicago Design Museum                                          | 2016-01-23T19:00:00-0600                                                                                  | Event        |          | facebookhttps://www.facebook.com/events/766302493513533/                                         | public://design-museum.jpg                                             |
      | Your Stories: Fanfiction 4 featuring the Masters of the Universe                     | 2016-02-21T19:00:00-0600                                                                                  | Event        |          | facebook eventhttps://www.facebook.com/events/1090914514287132/                                  | public://masters-universe.jpg                                          |
      | Your Stories: "THanks" w/ Tom Hanks Day (at Begyle Brewing)!                         | 2016-03-20T19:00:00-0500                                                                                  | Event        |          | https://www.facebook.com/events/166787277036218/                                                 | public://thanks.jpg                                                    |
      | Support us on Patreon                                                                | 2016-06-30T02:17:00-0500                                                                                  | Event        |          | https://www.patreon.com/nerdologues                                                              | public://patron_only.jpg                                               |
      | Your Stories: "I Thought I Knew" with Scott Whitehair and friends!                   | 2016-04-17T19:00:00-0500                                                                                  | Event        |          | https://www.facebook.com/events/833863660080022/                                                 | public://YourStorieslogo.jpg                                           |
      | Attend the Tale of Danny Tanner: A Full House Musical                                | 2016-05-07T22:30:00-0500 , 2016-05-29T22:30:00-0500                                                       | Event        |          | https://www.facebook.com/events/223979094632478/                                                 | public://FullHouse.jpg                                                 |
      | Cards Against Humanity Live                                                          | 2016-04-16T23:59:00-0500                                                                                  | Event        |          | http://ioimprov.com/chicago/show/cards-humanity-live/                                            | public://CAHLive.jpg                                                   |
      | Your Stories: "Making" with the Chicago Public Library Maker Lab                     | 2016-05-10T18:00:00-0500                                                                                  | Event        |          | https://www.facebook.com/events/1616790661979636/                                                | public://makerlab.png                                                  |
      | Your Stories: "I'm In" at the LakeFX Chicago 2016 Summit + Expo!                     | 2016-05-14T10:00:00-0500                                                                                  | Event        |          | https://www.facebook.com/events/1783640501872519/                                                | public://LakeFX.jpg                                                    |
      | The Nerdologues at Voodoo                                                            | 2016-06-17T22:00:00-0500                                                                                  | Event        |          | https://voodoocomedy.com/event/nerdologues-special-event/                                        | public://voodoo-940x529.jpg                                            |
      | Your Stories: "Take a Breather" with Breather & Common Threads!                      | 2016-05-27T20:00:00-0500                                                                                  | Event        |          | Tickets & more info here!http://commonthreads.org/events/Your-Stories:-Taking-A-Breather         | public://YourStories5.27.2016.jpg                                      |
      | Cards Against Humanity Live                                                          | 2016-06-25T23:55:00-0500                                                                                  | Event        |          | http://ioimprov.com/chicago/show/cards-humanity-live/2016-06-25/                                 | public://CAHLive.jpg                                                   |
      | Your Stories: "Grit" featuring Puck & Grind                                          | 2016-07-17T19:00:00-0500                                                                                  | Event        |          | https://www.facebook.com/events/1765860370315660/                                                | public://YourStorieslogo.jpg                                           |
      | Your Stories: "Intrigue" featuring the creators of Taylor Swift: Girl Detective      | 2016-08-21T19:00:00-0500                                                                                  | Event        |          | https://www.facebook.com/events/114715052305144/                                                 | public://intrigue.png                                                  |
      | Your Stories: Long Distance at UCB Sunset!                                           | 2016-09-19T20:30:00-0500                                                                                  | Event        |          | https://www.facebook.com/events/699237613563919/                                                 | public://ucbsunset.jpg                                                 |
      | Your Stories: Horror Stories 2                                                       | 2016-10-16T19:00:00-0500                                                                                  | Event        |          | https://www.facebook.com/events/1178649732196764/                                                | public://treehouse2.jpg                                                |

