Feature: Podcast Episode

  @api
  Scenario: Podcast Episode
    Given I am logged in as a user with the "administrator" role
    When I visit "admin/content-migration/podcast_episode"
    Then I should see the following table portion

    | Title                                                                    | Date Published | Podcast              | Podbean mp3                                                                | Link | Patreon link | File size | URI                                                                                                         |
    | Episode 007: Mayans and Missouri. Hold The Sour Cream.                   | 2009-10-04     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/9vigz2/Oberbeck.m4a             |      |              | 36.54 MB  | http://podcasts.nerdologues.com/poorchoicesshow/Oberbeck.mp3?m-4-a                                          |
    | Episode 008: How to sell a Hoosier a $300 Potato                         | 2009-10-11     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/spv394/JakeSchneider.m4a        |      |              | 40.91 MB  | http://podcasts.nerdologues.com/poorchoicesshow/JakeSchneider.mp3?m-4-a                                     |
    | Episode 009: The Rejection Show                                          | 2009-10-18     | Poor Choices Archive |                                                                            |      |              |           |                                                                                                             |
    | Episode 010: Take Out Your Tender                                        | 2009-10-25     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/dzhn49/ChrisBragg.m4a           |      |              | 36.5 MB   | http://podcasts.nerdologues.com/poorchoicesshow/ChrisBragg.mp3?m-4-a                                        |
    | Episode 011: The Halloween Hangover                                      | 2009-11-01     | Poor Choices Archive | http://www.podbean.com/empty/showelevenzach.mp3                            |      |              |           | http://podcasts.nerdologues.com/poorchoicesshow/showelevenzach.mp3                                          |
    | Episode 013: The Day The Clown Died                                      | 2009-11-16     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/pipdj/ryanmcgillen.m4a          |      |              | 37.17 MB  | http://podcasts.nerdologues.com/poorchoicesshow/ryanmcgillen.mp3?m-4-a                                      |
    | Episode 014: Florida is not The South                                    | 2009-11-23     | Poor Choices Archive | http://www.podbean.com/empty/showfourteenDan.mp3                           |      |              |           | http://podcasts.nerdologues.com/poorchoicesshow/showfourteenDan.mp3                                         |
    | Episode 015: Show Me All The Blueprints                                  | 2009-11-29     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/pdhuwv/jimmypennington.m4a      |      |              | 44.55 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jimmypennington.mp3?m-4-a                                   |
    | Episode 016: Tango, Sir? Or A Tale of Two Theaters                       | 2009-12-08     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/fu92iw/adalrifai.m4a            |      |              | 41.6 MB   | http://podcasts.nerdologues.com/poorchoicesshow/adalrifai.mp3?m-4-a                                         |
    | Episode 017: Ghost Ride The Razorback                                    | 2009-12-13     | Poor Choices Archive | http://www.podbean.com/empty/showseventeencraig.mp3                        |      |              |           | http://podcasts.nerdologues.com/poorchoicesshow/showseventeencraig.mp3                                      |
    | Episode 018: Unatainashow                                                | 2009-12-22     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/4nv4v3/jeffmurdoch.m4a          |      |              | 39.13 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jeffmurdoch.mp3?m-4-a                                       |
    | Episode 019: Malortnowski                                                | 2010-01-03     | Poor Choices Archive | http://www.podbean.com/empty/murnowski.mp3                                 |      |              |           | http://podcasts.nerdologues.com/poorchoicesshow/murnowski.mp3                                               |
    | Episode 020: Cooking With Oranges                                        | 2010-01-10     | Poor Choices Archive | http://www.podbean.com/empty/Wes_Haney_Show_Twenty.m4a                     |      |              |           | http://podcasts.nerdologues.com/poorchoicesshow/Wes_Haney_Show_Twenty.mp3?m-4-a                             |
    | The Best of Our Worst: Highlights of 2009                                | 2010-01-20     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/x94xxu/Poor_Choices_Best_Of.m4a |      |              | 32.08 MB  | http://podcasts.nerdologues.com/poorchoicesshow/Poor_Choices_Best_Of.mp3?m-4-a                              |
    | Episode 021: Marriage? Eh?                                               | 2010-01-24     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/jur3y/The_Scotts_Show21.m4a     |      |              | 33.54 MB  | http://podcasts.nerdologues.com/poorchoicesshow/The_Scotts_Show21.mp3?m-4-a                                 |
    | Episode 022: The Ballad of Phil Meister                                  | 2010-02-13     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/7ui72t/Phil_Poorshow.m4a        |      |              | 30.42 MB  | http://podcasts.nerdologues.com/poorchoicesshow/Phil_Poorshow.mp3?m-4-a                                     |
    | Episode 023: Assumption Junction                                         | 2010-02-21     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/x6xc8n/jonlangan.m4a            |      |              | 31.21 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jonlangan.mp3?m-4-a                                         |
    | Episode 024: Webbittude                                                  | 2010-02-28     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/vxyi4i/jamwebb.m4a              |      |              | 35.56 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jamwebb.mp3?m-4-a                                           |
    | Episode 025: Doughnuts, Dogs, and Del                                    | 2010-03-07     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/2vsjpn/JasonChin25.m4a          |      |              | 36.36 MB  | http://podcasts.nerdologues.com/poorchoicesshow/JasonChin25.mp3?m-4-a                                       |
    | Episode 026: Time Changes and Strange Places                             | 2010-03-16     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/q9sq2h/PaulJurwitz.m4a          |      |              | 32.85 MB  | http://podcasts.nerdologues.com/poorchoicesshow/PaulJurwitz.mp3?m-4-a                                       |
    | Episode 027: Stupid Nerdy Choices                                        | 2010-03-21     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/9fdmzs/ArnieshowTwo.m4a         |      |              | 35.5 MB   | http://podcasts.nerdologues.com/poorchoicesshow/ArnieshowTwo.mp3?m-4-a                                      |
    | Episode 28: Get In The Ring                                              | 2010-03-28     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/n3wiat/nickshow.m4a             |      |              | 30.47 MB  | http://podcasts.nerdologues.com/poorchoicesshow/nickshow.mp3?m-4-a                                          |
    | Episode 29: Detroit via Arrakis                                          | 2010-04-05     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/secft/ericrutherford.m4a        |      |              | 32.98 MB  | http://podcasts.nerdologues.com/poorchoicesshow/ericrutherford.mp3?m-4-a                                    |
    | Episode 30: Let’s Stay Together                                          | 2010-04-11     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/atw9dt/garyrichardson.m4a       |      |              | 31.69 MB  | http://podcasts.nerdologues.com/poorchoicesshow/garyrichardson.mp3?m-4-a                                    |
    | Episode 31: The Shock T’s                                                | 2010-04-11     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/7vx2dd/shocktsshowthirty.m4a    |      |              | 21.13 MB  | http://podcasts.nerdologues.com/poorchoicesshow/shocktsshowthirty.mp3?m-4-a                                 |
    | Episode 32: Sunday with St. Clair                                        | 2010-04-18     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/titmqq/stclair.m4a              |      |              | 32.92 MB  | http://podcasts.nerdologues.com/poorchoicesshow/stclair.mp3?m-4-a                                           |
    | Episode 33: Michael Pizza                                                | 2010-04-25     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/8djsys/mpizza.m4a               |      |              | 27.35 MB  | http://podcasts.nerdologues.com/poorchoicesshow/mpizza.mp3?m-4-a                                            |
    | Episode 34: You Are Horribly Wrong About Every Subject You Talk About    | 2010-05-03     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/wyvqa9/jasonanfinson.m4a        |      |              | 33.16 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jasonanfinson.mp3?m-4-a                                     |
    | Episode 35: Making It Michigan                                           | 2010-05-10     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/v8ed5v/joeavella.m4a            |      |              | 28.95 MB  | http://podcasts.nerdologues.com/poorchoicesshow/joeavella.mp3?m-4-a                                         |
    | Episode 36: Nick Schaefer IN SPACE!!!!                                   | 2010-05-16     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/rey9yg/nickschaffer.m4a         |      |              | 81.65 MB  | http://podcasts.nerdologues.com/poorchoicesshow/nickschaffer.mp3?m-4-a                                      |
    | Episode 37: Hey You Guys. DUFFY                                          | 2010-05-23     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/p5gfxf/KateDuffy.m4a            |      |              | 67.76 MB  | http://podcasts.nerdologues.com/poorchoicesshow/Episode37_HeyYouGuysDUFFY.mp3?m-4-a                         |
    | Episode 38: Margolis and Reisman. Reisman and Margolis                   | 2010-05-30     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/bddvfu/margolisandreisman.m4a   |      |              | 23.72 MB  | http://podcasts.nerdologues.com/poorchoicesshow/margolisandreisman.mp3?m-4-a                                |
    | Episode 039: Williams, Martinez, and Doc Holliday                        | 2010-06-06     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/sgfrvq/williamsmartinez.m4a     |      |              | 30.29 MB  | http://podcasts.nerdologues.com/poorchoicesshow/williamsmartinez.mp3?m-4-a                                  |
    | Episode 40: Chips and Dip with Claymore                                  | 2010-06-14     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/n7mj3v/claymore.m4a             |      |              | 74.52 MB  | http://podcasts.nerdologues.com/poorchoicesshow/Episode-40-Chips-and-Dip-with-Claymore.mp3?m-4-a            |
    | Episode 41: Father’s Day with Joe Bill                                   | 2010-06-20     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/9cs29t/JoeBill.m4a              |      |              | 80.72 MB  | http://podcasts.nerdologues.com/poorchoicesshow/Episode-41-Father-s-Day-with-Joe-Bill.mp3?m-4-a             |
    | Episode 42: Matt Bivins and the Dangerous Children                       | 2010-07-05     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/i9nzq/bivins.m4a                |      |              | 76.53 MB  | http://podcasts.nerdologues.com/poorchoicesshow/Episode-42-Matt-Bivins-and-the-Dangerous-Children.mp3?m-4-a |
    | Episode 43: Jimmy’s Got A Gun                                            | 2010-07-11     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/z3pwe/penningtonpart2.m4a       |      |              | 79.17 MB  | http://podcasts.nerdologues.com/poorchoicesshow/Episode43_Jimmy_sGotAGun.mp3?m-4-a                          |
    | Episode 44: Major League Megan Johns                                     | 2010-07-19     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/rdrja/meganjohns.m4a            |      |              | 86.99 MB  | http://podcasts.nerdologues.com/poorchoicesshow/Episode-44-Major-League-Megan-Johns.mp3?m-4-a               |
    | Episode 45: Basements in Pilson with John Brewster                       | 2010-07-25     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/r4e4zc/johnbrestwer.m4a         |      |              | 81.23 MB  | http://podcasts.nerdologues.com/poorchoicesshow/Episode-45_Basements-in-Pilson-with-John-Brewster.mp3?m-4-a |
    | Episode 46: The History of Matt Owens                                    | 2010-08-03     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/bqwnqv/mattandmarkaug1.m4a      |      |              | 68.3 MB   | http://podcasts.nerdologues.com/poorchoicesshow/Episode-46_The-History-of-Matt-Owens.mp3?m-4-a              |
    | Episode 47: Casa Bonita con Joseph Phillips                              | 2010-08-16     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/43afd/joephillips.m4a           |      |              | 67 MB     | http://podcasts.nerdologues.com/poorchoicesshow/Episode47_CasaBonitaconJosephPhillips.mp3?m-4-a             |
    | Episode 48: The Lives and Ladies of Roy Ivy                              | 2010-08-23     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/5yprsa/royivy.m4a               |      |              | 83.38 MB  | http://podcasts.nerdologues.com/poorchoicesshow/Episode48_TheLivesandLadiesofRoyIvy.mp3?m-4-a               |
    | Episode 49: One Year of Poor Choices                                     | 2010-09-02     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/e8558a/oneyear.m4a              |      |              |           | http://podcasts.nerdologues.com/poorchoicesshow/oneyear.mp3?m-4-a                                           |
    | Episode 49.5: Bob and Stacey of Curious Comedy                           | 2010-09-08     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/2yq5t6/bobandstacey.m4a         |      |              |           | http://podcasts.nerdologues.com/poorchoicesshow/bobandstacey.mp3?m-4-a                                      |
    | Episode 50: Learning Names with Seth Weitberg                            | 2010-10-17     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/ecx6qx/weitberg.m4a             |      |              |           | http://podcasts.nerdologues.com/poorchoicesshow/weitberg.mp3?m-4-a                                          |
    | Episode 51: Our Long Strange Trips                                       | 2010-10-27     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/mffbfj/ericeyerman.m4a          |      |              | 84.36 MB  | http://podcasts.nerdologues.com/poorchoicesshow/ericeyerman.mp3?m-4-a                                       |
    | Episode 52: Blackout Presents: Shake Yo Nuts                             | 2010-10-31     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/7uvuwb/blackout.m4a             |      |              | 71.77 MB  | http://podcasts.nerdologues.com/poorchoicesshow/blackout.mp3?m-4-a                                          |
    | Episode 53: The Katydids Win A Date With Pennington                      | 2010-11-07     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/8hnpvt/katiedids.m4a            |      |              | 64.16 MB  | http://podcasts.nerdologues.com/poorchoicesshow/katiedids.mp3?m-4-a                                         |
    | Episode 54: The Teachings of Arnett                                      | 2010-11-14     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/87t9xi/arnett.m4a               |      |              | 80.09 MB  | http://podcasts.nerdologues.com/poorchoicesshow/arnett.mp3?m-4-a                                            |
    | Episode 55: Zombie Potter                                                | 2010-11-21     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/43tak3/mattandmarknov.m4a       |      |              | 70.88 MB  | http://podcasts.nerdologues.com/poorchoicesshow/mattandmarknov.mp3?m-4-a                                    |
    | Episode 56: Crankcast with Teenager of the Year                          | 2010-11-28     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/vgxjk/teenageroftheyear.m4a     |      |              | 88.06 MB  | http://podcasts.nerdologues.com/poorchoicesshow/teenageroftheyear.mp3?m-4-a                                 |
    | Episode 57: The Gathering of Jerkalos                                    | 2010-12-12     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/9jb7z6/nickhausnantwo.m4a       |      |              | 82.53 MB  | http://podcasts.nerdologues.com/poorchoicesshow/nickhausnantwo.mp3?m-4-a                                    |
    | Episode 58: Messing with Poor Choices                                    | 2010-12-19     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/4i3si3/messing.m4a              |      |              |           | http://podcasts.nerdologues.com/poorchoicesshow/messing.mp3?m-4-a                                           |
    | Episode 59: Lady Esther                                                  | 2010-12-29     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/h5sk4f/esther.m4a               |      |              | 73.64 MB  | http://podcasts.nerdologues.com/poorchoicesshow/esther.mp3?m-4-a                                            |
    | Episode 60: Matt has a Text Plan and Mark Got Sunburnt                   | 2011-02-12     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/rx42jc/showsixtytwo.m4a         |      |              | 24.28 MB  | http://podcasts.nerdologues.com/poorchoicesshow/showsixtytwo.mp3?m-4-a                                      |
    | Episode 61: Jason Chin Explains Things To You                            | 2011-02-19     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/faukgi/Chin2k11.m4a             |      |              | 68.21 MB  | http://podcasts.nerdologues.com/poorchoicesshow/Chin2k11.mp3?m-4-a                                          |
    | Episode 62: Classic Mike Klasek                                          | 2011-02-26     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/c35ai2/mikeklasek.m4a           |      |              | 81.19 MB  | http://podcasts.nerdologues.com/poorchoicesshow/mikeklasek.mp3?m-4-a                                        |
    | Episode 63: Today’s Tom Sawyer: Jay Olson                                | 2011-03-04     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/wy436/jayolson.m4a              |      |              | 79.6 MB   | http://podcasts.nerdologues.com/poorchoicesshow/jayolson.mp3?m-4-a                                          |
    | Episode 64: The Life and Legend of Del Close                             | 2011-03-08     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/8nrry/DelCloseandCharna.mp3     |      |              | 30.12 MB  | http://podcasts.nerdologues.com/poorchoicesshow/DelCloseandCharna.mp3                                       |
    | Episode 65: Backstage at The Del Awards                                  | 2011-03-10     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/zjh224/Delawards2.mp3           |      |              | 35.42 MB  | http://podcasts.nerdologues.com/poorchoicesshow/Delawards2.mp3                                              |
    | Episode 66: Sam Weiner is Not 7 Feet Tall                                | 2011-03-17     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/stsrst/samweiner.m4a            |      |              | 33.12 MB  | http://podcasts.nerdologues.com/poorchoicesshow/samweiner.mp3?m-4-a                                         |
    | Episode 67: Lessons from George McAuliffe                                | 2011-03-26     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/urhaaw/george.m4a               |      |              | 80.73 MB  | http://podcasts.nerdologues.com/poorchoicesshow/george.mp3?m-4-a                                            |
    | Episode 68: Candy Hat                                                    | 2011-03-29     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/ekb85/MOREBRAGG.mp3             |      |              | 21.82 MB  | http://podcasts.nerdologues.com/poorchoicesshow/MOREBRAGG.mp3                                               |
    | Episode 70: Seriously: Seth and Kellen                                   | 2011-04-07     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/987c86/kellenandseth.m4a        |      |              | 28.72 MB  | http://podcasts.nerdologues.com/poorchoicesshow/kellenandseth.mp3?m-4-a                                     |
    | Episode 71: Talking Treasure With Andy St. Clair                         | 2011-04-14     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/ybwm32/andystclairpart2.m4a     |      |              | 95.82 MB  | http://podcasts.nerdologues.com/poorchoicesshow/andystclairpart2.mp3?m-4-a                                  |
    | Episode 72: Trevor with an M and Dan with a Y                            | 2011-04-21     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/57u8uw/danandtrevor.m4a         |      |              | 81.54 MB  | http://podcasts.nerdologues.com/poorchoicesshow/danandtrevor.mp3?m-4-a                                      |
    | Episode 73: Action Comics Presents: Linus Lee                            | 2011-05-02     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/gmysw/linuslee.m4a              |      |              | 91.61 MB  | http://podcasts.nerdologues.com/poorchoicesshow/linuslee.mp3?m-4-a                                          |
    | Episode 74: Summer Movies                                                | 2011-05-17     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/rs983c/summermoviepreview.m4a   |      |              | 83.71 MB  | http://podcasts.nerdologues.com/poorchoicesshow/summermoviepreview.mp3?m-4-a                                |
    | Episode 75: The Dulcet Tones of Gary Tiedemann                           | 2011-05-29     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/kbekvv/garytiedman.m4a          |      |              | 74.13 MB  | http://podcasts.nerdologues.com/poorchoicesshow/garytiedman.mp3?m-4-a                                       |
    | Episode 76: Kevin Mullaney is a Joy…Joy                                  | 2011-06-07     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/utshhn/kevinmullany.m4a         |      |              | 86.97 MB  | http://podcasts.nerdologues.com/poorchoicesshow/kevinmullany.mp3?m-4-a                                      |
    | Episode 77: Crom, Cats, Conan, and Coney                                 | 2011-06-24     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/zc3f45/mattandmarkjune.m4a      |      |              | 61.58 MB  | http://podcasts.nerdologues.com/poorchoicesshow/mattandmarkjune.mp3?m-4-a                                   |
    | Episode 78: Living Without Us                                            | 2011-07-09     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/8ppsc/mattandmarkjuly.mp3       |      |              | 30.42 MB  | http://podcasts.nerdologues.com/poorchoicesshow/mattandmarkjuly.mp3                                         |
    | Episode 79: Short Shopping With Mel Evans                                | 2011-07-24     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/22cfm9/melevansfinal.mp3        |      |              | 31.66 MB  | http://podcasts.nerdologues.com/poorchoicesshow/melevansfinal.mp3                                           |
    | Episode 80: The Quiet Storm with Brett Lyons                             | 2011-08-03     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/4cz7ms/brettlyons.mp3           |      |              | 34.43 MB  | http://podcasts.nerdologues.com/poorchoicesshow/brettlyons.mp3                                              |
    | Episode 81: Facts About Facklis                                          | 2011-08-14     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/g5mxix/dinafacklis.m4a          |      |              | 88.02 MB  | http://podcasts.nerdologues.com/poorchoicesshow/dinafacklis.mp3?m-4-a                                       |
    | Episode 82: The Talented Mark                                            | 2011-08-17     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/nf2uv8/markraterman.m4a         |      |              | 22.06 MB  | http://podcasts.nerdologues.com/poorchoicesshow/markraterman.mp3?m-4-a                                      |
    | Episode 83: Jim Carlson’s Comeback                                       | 2011-08-18     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/2qyjbt/jimcarlson.m4a           |      |              | 32.12 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jimcarlson.mp3?m-4-a                                        |
    | Episode 84: Who Dat? It’s Anthony Leblanc                                | 2011-08-22     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/rxmr/anthoneyleblanc.mp3        |      |              | 34.51 MB  | http://podcasts.nerdologues.com/poorchoicesshow/anthoneyleblanc.mp3                                         |
    | Episode 85: The Chicago Comedy Festival                                  | 2011-08-24     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/rmmbpr/ccfest.mp3               |      |              | 22.79 MB  | http://podcasts.nerdologues.com/poorchoicesshow/ccfest.mp3                                                  |
    | Episode 86: A Real Maverick                                              | 2011-08-25     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/u7i3em/johnsabine.mp3           |      |              | 29.85 MB  | http://podcasts.nerdologues.com/poorchoicesshow/johnsabine.mp3                                              |
    | Episode 87: Eating Wings with Danny Mora                                 | 2011-08-29     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/eu2x73/dannymora.mp3            |      |              | 26.71 MB  | http://podcasts.nerdologues.com/poorchoicesshow/dannymora.mp3                                               |
    | Episode 88: A Time Out With Steve Heisler                                | 2011-08-31     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/zcr4b/steveheisler.mp3          |      |              | 23.84 MB  | http://podcasts.nerdologues.com/poorchoicesshow/steveheisler.mp3                                            |
    | Episode 89: Oh Bother….Brendan Jennings                                  | 2011-09-02     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/8wda5x/brandonjennings.mp3      |      |              | 28.01 MB  | http://podcasts.nerdologues.com/poorchoicesshow/brandonjennings.mp3                                         |
    | Episode 90: Labor Day with Adal Rifai                                    | 2011-09-05     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/75y468/adalrifaishowtwo.mp3     |      |              | 31.97 MB  | http://podcasts.nerdologues.com/poorchoicesshow/adalrifaishowtwo.mp3                                        |
    | Episode 91: The Best Friggin’ Time With Beth Melewski                    | 2011-09-07     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/hpgh7a/bethmelewski.mp3         |      |              | 24.8 MB   | http://podcasts.nerdologues.com/poorchoicesshow/bethmelewski.mp3                                            |
    | Episode 92: Slowing Things Down with Jimmy Carrane                       | 2011-09-09     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/k926k4/jimmycarrane.mp3         |      |              | 35.11 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jimmycarrane.mp3                                            |
    | Episode 93: The Matt Young Strikes Back                                  | 2011-09-12     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/dhez6k/mattyoung.mp3            |      |              | 31.24 MB  | http://podcasts.nerdologues.com/poorchoicesshow/mattyoung.mp3                                               |
    | Episode 94: The Architecture of Peyton Brown                             | 2011-09-13     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/tqjv5h/peytonbrown.mp3          |      |              | 27.39 MB  | http://podcasts.nerdologues.com/poorchoicesshow/peytonbrown.mp3                                             |
    | Episode 95: Laying Down The Law with Kara Jakubec                        | 2011-09-16     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/8uy532/karajubec.mp3            |      |              | 35.12 MB  | http://podcasts.nerdologues.com/poorchoicesshow/karajubec.mp3                                               |
    | Episode 96: Do You Like Oprah, Tim Paul?                                 | 2011-09-19     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/iicfr3/timpaul.mp3              |      |              | 33.21 MB  | http://podcasts.nerdologues.com/poorchoicesshow/timpaul.mp3                                                 |
    | Episode 97: The Return of Jake Schneider                                 | 2011-09-21     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/5vgrk/jakeschneidertwo.mp3      |      |              | 26.51 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jakeschneidertwo.mp3                                        |
    | Episode 98: Buy Cameron Esposito’s Album on iTunes with Cameron Esposito | 2011-09-23     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/ektss/cameronesposito.mp3       |      |              | 27.36 MB  | http://podcasts.nerdologues.com/poorchoicesshow/cameronesposito.mp3                                         |
    | Episode 99: Behind The Steel Curtain with Bethany Remely                 | 2011-09-26     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/uksdrq/bethanyremely.mp3        |      |              | 32.31 MB  | http://podcasts.nerdologues.com/poorchoicesshow/bethanyremely.mp3                                           |
    | Episode 100: Being Blue With Emily Wilson                                | 2011-09-28     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/cpc9fj/emilywilson.mp3          |      |              | 30.63 MB  | http://podcasts.nerdologues.com/poorchoicesshow/emilywilson.mp3                                             |
    | Episode 101: Bearing Down With Katie Rich                                | 2011-09-30     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/ab64br/katierich.mp3            |      |              | 1.09 KB   | http://podcasts.nerdologues.com/poorchoicesshow/katierich.mp3                                               |
    | Episode 102: The Shop With Patrick Rowland                               | 2011-10-03     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/zx5zmu/patrickrowland.mp3       |      |              | 26.46 MB  | http://podcasts.nerdologues.com/poorchoicesshow/patrickrowland.mp3                                          |
    | Episode 103: Poor Choices Presents Jeff Griggs                           | 2011-10-05     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/a88fsa/jeffgriggs.mp3           |      |              | 43.37 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jeffgriggs.mp3                                              |
    | Episode 104: It’s Always Sunny With Wes Needham                          | 2011-10-10     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/rfgfwh/jeffneedham.mp3          |      |              | 29.18 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jeffneedham.mp3                                             |
    | Episode 105: It’s a Small World with Aidy Bryant                         | 2011-10-12     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/j68maf/aidybyrant.mp3           |      |              | 28.27 MB  | http://podcasts.nerdologues.com/poorchoicesshow/aidybyrant.mp3                                              |
    | Episode 106: Vocal Envy with Ross Bryant                                 | 2011-10-17     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/th3c8a/rossbyrant.mp3           |      |              | 27.13 MB  | http://podcasts.nerdologues.com/poorchoicesshow/rossbyrant.mp3                                              |
    | Episode 107: The Magic of John Sturk                                     | 2011-10-19     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/yr5bi6/johnsturk.mp3            |      |              | 29.6 MB   | http://podcasts.nerdologues.com/poorchoicesshow/johnsturk.mp3                                               |
    | Episode 108: Two Hours With Conner O’Malley Part One                     | 2011-10-24     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/stcr53/conneromalley.mp3        |      |              | 27.73 MB  | http://podcasts.nerdologues.com/poorchoicesshow/conneromalley.mp3                                           |
    | Episode 109: Even More O’Malley                                          | 2011-10-26     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/wkjgva/conneromalleyp2.mp3      |      |              | 26.62 MB  | http://podcasts.nerdologues.com/poorchoicesshow/conneromalleyp2.mp3                                         |
    | Episode 111: Weissoween                                                  | 2011-10-31     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/i2jx8q/juliaweiss.mp3           |      |              | 34.08 MB  | http://podcasts.nerdologues.com/poorchoicesshow/juliaweiss.mp3                                              |
    | Episode 110: Eric Lindberg, Baby                                         | 2011-11-02     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/964iex/ericlindberg.mp3         |      |              | 29.65 MB  | http://podcasts.nerdologues.com/poorchoicesshow/ericlindberg.mp3                                            |
    | Episode 112: The Opinions of Greg Kot                                    | 2011-11-07     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/4tgq7y/kottad1.mp3              |      |              | 29.32 MB  | http://podcasts.nerdologues.com/poorchoicesshow/kottad1.mp3                                                 |
    | Episode 113: Impressing Thea Lux                                         | 2011-11-09     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/t8q27q/thealux.mp3              |      |              | 26.6 MB   | http://podcasts.nerdologues.com/poorchoicesshow/thealux.mp3                                                 |
    | Episode 114: Dubstepping With Kristen Studard                            | 2011-11-13     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/cu7yq4/kristenstuddard.mp3      |      |              | 28.58 MB  | http://podcasts.nerdologues.com/poorchoicesshow/kristenstuddard.mp3                                         |
    | Episode 115: Going To Denver with Nnamdi Ngwe                            | 2011-11-16     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/76v3s4/nmadi.mp3                |      |              | 25.73 MB  | http://podcasts.nerdologues.com/poorchoicesshow/nmadi.mp3                                                   |
    | Episode 116: Hey! Colt Cabana                                            | 2011-11-21     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/3psbc3/colt_cabana.mp3          |      |              | 31.42 MB  | http://podcasts.nerdologues.com/poorchoicesshow/colt_cabana.mp3                                             |
    | Episode 117: Flotilla with Daniel Haight                                 | 2011-11-23     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/4z7q7f/flotilla.mp3             |      |              | 23.98 MB  | http://podcasts.nerdologues.com/poorchoicesshow/flotilla.mp3                                                |
    | Episode 118: Hoops With Tim Baltz                                        | 2011-11-28     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/pn3fr7/timbaltz.mp3             |      |              | 34.81 MB  | http://podcasts.nerdologues.com/poorchoicesshow/timbaltz.mp3                                                |
    | Episode 119: Left For Dead with Sarah Maher                              | 2011-12-01     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/94ys9w/sarahmaher.mp3           |      |              | 28.66 MB  | http://podcasts.nerdologues.com/poorchoicesshow/sarahmaher.mp3                                              |
    | Episode 120: All Matt Ulrich Got Was This Podcast                        | 2011-12-05     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/cir2zh/mattulrich.mp3           |      |              | 30.95 MB  | http://podcasts.nerdologues.com/poorchoicesshow/mattulrich.mp3                                              |
    | Episode 121: Pulling Jared Jeffries Into Focus                           | 2011-12-07     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/7u27vt/jaredjeffires.mp3        |      |              | 35.04 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jaredjeffires.mp3                                           |
    | December 2011 Part 1                                                     | 2011-12-10     | Your Stories         | http://yourstories.podbean.com/mf/feed/n9n49h/Decemberpart1.mp3            |      |              | 45.29 MB  | https://podcasts.nerdologues.com/yourstories/Decemberpart1.mp3                                              |
    | Episode 122: Reel Talk With Ted Tremper                                  | 2011-12-12     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/wnnh6z/tedtremper2.mp3          |      |              | 39.39 MB  | http://podcasts.nerdologues.com/poorchoicesshow/tedtremper2.mp3                                             |
    | Episode 123: Close Quarters With Farrell Walsh                           | 2011-12-14     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/uiwzg/farrellwalsh.mp3          |      |              | 26.81 MB  | http://podcasts.nerdologues.com/poorchoicesshow/farrellwalsh.mp3                                            |
    | December 2011 Part 2                                                     | 2011-12-15     | Your Stories         | http://yourstories.podbean.com/mf/feed/4wssix/Decemberpart2.mp3            |      |              | 44.33 MB  | https://podcasts.nerdologues.com/yourstories/Decemberpart2.mp3                                              |
    | Episode 124: Day Trading with Mike Johnson                               | 2011-12-19     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/fjydma/mikejohnson.mp3          |      |              | 27.39 MB  | http://podcasts.nerdologues.com/poorchoicesshow/mikejohnson.mp3                                             |
    | Epsiode 125: Hey Kathy with Kate Lambert                                 | 2011-12-21     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/beewsi/katelambert.mp3          |      |              | 26.36 MB  | http://podcasts.nerdologues.com/poorchoicesshow/katelambert.mp3                                             |
    | Episode 126: Boxing Day with Colleen Doyle                               | 2011-12-26     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/y3hz58/colleendoyle.mp3         |      |              | 26.46 MB  | http://podcasts.nerdologues.com/poorchoicesshow/colleendoyle.mp3                                            |
    | Episode 127: More Talk With Scott Morehead                               | 2011-12-28     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/mh6tx9/scottmorehead.mp3        |      |              | 26.41 MB  | http://podcasts.nerdologues.com/poorchoicesshow/scottmorehead.mp3                                           |
    | January 2012                                                             | 2012-01-01     | Your Stories         | http://yourstories.podbean.com/mf/feed/qksrjs/January.mp3                  |      |              | 44.8 MB   | https://podcasts.nerdologues.com/yourstories/January.mp3                                                    |
    | Episode 128: Yelling With Jason Shotts                                   | 2012-01-03     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/nrnbpv/JasonShotts.mp3          |      |              | 32.83 MB  | http://podcasts.nerdologues.com/poorchoicesshow/JasonShotts.mp3                                             |
    | Episode 129: The Upstairs Year In Review                                 | 2012-01-04     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/g5fuas/upstairs.mp3             |      |              | 29.87 MB  | http://podcasts.nerdologues.com/poorchoicesshow/upstairs.mp3                                                |
    | VIDEO: Girl in a Comic Book Shop                                         | 2012-01-04     | Your Stories         |                                                                            |      |              |           |                                                                                                             |
    | NEW VENUE: The Upstairs Gallery                                          | 2012-01-06     | Your Stories         |                                                                            |      |              |           |                                                                                                             |
    | Episode 130: Thirty One Flavors of Mary Sohn                             | 2012-01-10     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/uwzyhk/marysohn.mp3             |      |              | 28.36 MB  | http://podcasts.nerdologues.com/poorchoicesshow/marysohn.mp3                                                |
    | Episode 131: Exquisite Guest with Tyler Smith                            | 2012-01-12     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/63dyt/tylersmith.mp3            |      |              | 28.71 MB  | http://podcasts.nerdologues.com/poorchoicesshow/tylersmith.mp3                                              |
    | Episode 132: The Enthusiasm of Jorin Garguilo                            | 2012-01-17     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/dmfrgq/joringarguilo.mp3        |      |              | 30.36 MB  | http://podcasts.nerdologues.com/poorchoicesshow/joringarguilo.mp3                                           |
    | Episode 133: The Full Steve Nelson                                       | 2012-01-23     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/js3tyt/stevenelson.mp3          |      |              | 26.78 MB  | http://podcasts.nerdologues.com/poorchoicesshow/stevenelson.mp3                                             |
    | Episode 134: An Ivy League Education With Karisa Bruin                   | 2012-01-26     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/c485uy/kariasabruin.mp3         |      |              | 30.26 MB  | http://podcasts.nerdologues.com/poorchoicesshow/kariasabruin.mp3                                            |
    | February 2012 Part 1                                                     | 2012-02-01     | Your Stories         | http://yourstories.podbean.com/mf/feed/nkk2in/FebruaryPart1.mp3            |      |              | 36.81 MB  | https://podcasts.nerdologues.com/yourstories/FebruaryPart1.mp3                                              |
    | February 2012 Part 2                                                     | 2012-02-15     | Your Stories         | http://yourstories.podbean.com/mf/feed/rzyu39/FebruaryPart2.mp3            |      |              | 38.35 MB  | https://podcasts.nerdologues.com/yourstories/FebruaryPart2.mp3                                              |
    | Valentines Day With Jimmy Pennington                                     | 2012-02-15     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/f9h892/jimmypenington2k12.mp3   |      |              | 31.99 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jimmypenington2k12.mp3                                      |
    | Episode 136: The Irene Marquette Experience                              | 2012-02-21     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/rhwqvy/irenemarquette.mp3       |      |              | 33.27 MB  | http://podcasts.nerdologues.com/poorchoicesshow/irenemarquette.mp3                                          |
    | Episode 137: Changing Channels With Tim Paul                             | 2012-02-28     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/fnr7u/timpaulfebruary2k12.mp3   |      |              | 54.31 MB  | http://podcasts.nerdologues.com/poorchoicesshow/timpaulfebruary2k12.mp3                                     |
    | March 2012 - The Music of Our Nerdy Hearts                               | 2012-03-01     | Your Stories         | http://yourstories.podbean.com/mf/feed/cyir2w/March.mp3                    |      |              | 62.62 MB  | https://podcasts.nerdologues.com/yourstories/March.mp3                                                      |
    | Episode 138: Driving The Baseline With Kevin Sciretta                    | 2012-03-05     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/i9p3hk/kevin_scrietta.mp3       |      |              | 40.04 MB  | http://podcasts.nerdologues.com/poorchoicesshow/kevin_scrietta.mp3                                          |
    | Episode 139: Te-Has with Josh Segovia                                    | 2012-03-14     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/8trbs4/joshsegovia.mp3          |      |              | 1.09 KB   | http://podcasts.nerdologues.com/poorchoicesshow/joshsegovia.mp3                                             |
    | BONUS Episode: Live at Challengers Comics!                               | 2012-03-15     | Your Stories         | http://yourstories.podbean.com/mf/feed/z4kpj/Challengers.mp3               |      |              | 52.51 MB  | https://podcasts.nerdologues.com/yourstories/Challengers.mp3                                                |
    | Episode 140: Getting a 7.6 Rating from Dave Maher                        | 2012-03-19     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/c24bwd/davemaher.mp3            |      |              | 46.29 MB  | http://podcasts.nerdologues.com/poorchoicesshow/davemaher.mp3                                               |
    | Episode 141: The Current Mrs. Scott with Jo Scott                        | 2012-03-22     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/bc5w/joscottmarch17.mp3         |      |              | 34.65 MB  | http://podcasts.nerdologues.com/poorchoicesshow/joscottmarch17.mp3                                          |
    | Episode 142: Master of Direction with Joe Avella                         | 2012-03-27     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/5z78z/joeavellamarch17.mp3      |      |              | 35.55 MB  | http://podcasts.nerdologues.com/poorchoicesshow/joeavellamarch17.mp3                                        |
    | Episode 143: Singing Along with Mansical                                 | 2012-03-29     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/c6a4tg/mansicamarch.mp3         |      |              | 30.26 MB  | http://podcasts.nerdologues.com/poorchoicesshow/mansicamarch.mp3                                            |
    | April 2012 Part 1: Teach Your Children Well, Etc.                        | 2012-04-01     | Your Stories         | http://yourstories.podbean.com/mf/feed/z6sfiq/AprilPart1.mp3               |      |              | 40.58 MB  | https://podcasts.nerdologues.com/yourstories/AprilPart1.mp3                                                 |
    | Episode 144: Jayhawking with Nathan Jansen                               | 2012-04-03     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/z6aqnb/nathanjansonmarch18.mp3  |      |              | 28.17 MB  | http://podcasts.nerdologues.com/poorchoicesshow/nathanjansonmarch18.mp3                                     |
    | Episode 145: Taco Talk With Greg Hess                                    | 2012-04-05     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/ccvsvz/greghess312.mp3          |      |              | 33 MB     | http://podcasts.nerdologues.com/poorchoicesshow/greghess312.mp3                                             |
    | Episode 146: Is That… It’s Daniel Strauss’ Music                         | 2012-04-10     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/ephmw/danielstraussmarch.mp3    |      |              | 39.95 MB  | http://podcasts.nerdologues.com/poorchoicesshow/danielstraussmarch.mp3                                      |
    | Check out Dwight and Eric on the Unshaven Rant-Cast!                     | 2012-04-10     | Your Stories         |                                                                            |      |              |           |                                                                                                             |
    | Episode 147: The Show Choir with Katie O’Brien                           | 2012-04-12     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/xa7etx/katieobrien.mp3          |      |              | 25.91 MB  | http://podcasts.nerdologues.com/poorchoicesshow/katieobrien.mp3                                             |
    | April 2012 Part 2: Krazy Kustomers and Kool Kids                         | 2012-04-16     | Your Stories         | http://yourstories.podbean.com/mf/feed/ne8akp/April2.mp3                   |      |              | 44.88 MB  | https://podcasts.nerdologues.com/yourstories/April2.mp3                                                     |
    | Episode 148: Chemical Equations with Jason Geis of pH                    | 2012-04-16     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/nqfsc/jasongeisapril.mp3        |      |              | 29.92 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jasongeisapril.mp3                                          |
    | Episode 149: Scoring Time with Jesse Case                                | 2012-04-19     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/mbwm65/jessecase.mp3            |      |              | 27.24 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jessecase.mp3                                               |
    | May Preview featuring the Fantastic Four!                                | 2012-04-24     | Your Stories         | http://yourstories.podbean.com/mf/feed/t54vt/Marcpreview.mp3               |      |              | 4.1 MB    | https://podcasts.nerdologues.com/yourstories/Marcpreview.mp3                                                |
    | Episode 150: Where Are We At with Jamison Webb                           | 2012-04-24     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/82h4xb/jamisonwebb.mp3          |      |              | 43.61 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jamisonwebb.mp3                                             |
    | Episode 151: Noshing with Jo Feldman                                     | 2012-04-26     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/6ax5ev/jofeldman.mp3            |      |              | 33.49 MB  | http://podcasts.nerdologues.com/poorchoicesshow/jofeldman.mp3                                               |
    | May 2012 Part 1: Let’s Talk About Sex                                    | 2012-05-01     | Your Stories         | http://yourstories.podbean.com/mf/feed/6mgb9n/Maypart1.mp3                 |      |              | 55.6 MB   | https://podcasts.nerdologues.com/yourstories/Maypart1.mp3                                                   |
    | Episode 152: The Magic of Chris Witaske                                  | 2012-05-01     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/def4zv/chriswitaske.mp3         |      |              | 34.29 MB  | http://podcasts.nerdologues.com/poorchoicesshow/chriswitaske.mp3                                            |
    | Episode 153: The Other Other Ghosts with The Other Other Guys            | 2012-05-03     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/t3y4v/otherotherguys.mp3        |      |              | 36.6 MB   | http://podcasts.nerdologues.com/poorchoicesshow/otherotherguys.mp3                                          |
    | Episode 154: All The Worlds A Stage with Brian Posen                     | 2012-05-08     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/r8vkr9/brianposen.mp3           |      |              | 29.88 MB  | http://podcasts.nerdologues.com/poorchoicesshow/brianposen.mp3                                              |
    | Episode 155: If It Bleeds It Leads With Ben Bowman                       | 2012-05-10     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/nsnt5t/benbowman.mp3            |      |              | 42.62 MB  | http://podcasts.nerdologues.com/poorchoicesshow/benbowman.mp3                                               |
    | May 2012 Part 2: Like Triple X, But With Less Vin Diesel                 | 2012-05-15     | Your Stories         | http://yourstories.podbean.com/mf/feed/u7vk52/Maypart2.mp3                 |      |              | 54.16 MB  | https://podcasts.nerdologues.com/yourstories/Maypart2.mp3                                                   |
    | Episode 156: Going To Potbelly’s With Pat Dwyer                          | 2012-05-15     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/pf87jq/patdwyer.mp3             |      |              | 35.79 MB  | http://podcasts.nerdologues.com/poorchoicesshow/patdwyer.mp3                                                |
    | Episode 157: On Tour With The Shock T’s                                  | 2012-05-17     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/5txxvh/shockts.mp3              |      |              | 60.93 MB  | http://podcasts.nerdologues.com/poorchoicesshow/shockts.mp3                                                 |
    | Episode 158: Directing Ryan Patrick Dolan                                | 2012-05-22     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/k33dvk/ryandolan.mp3            |      |              | 25.07 MB  | http://podcasts.nerdologues.com/poorchoicesshow/ryandolan.mp3                                               |
    | Episode 159: Waiting with Mike Marunowski                                | 2012-05-24     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/8jkz22/mikemurnowski.mp3        |      |              | 29.4 MB   | http://podcasts.nerdologues.com/poorchoicesshow/mikemurnowski.mp3                                           |
    | Episode 160: At The Playground with Matt Barbera                         | 2012-05-29     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/5bdi3/mattbarbera.mp3           |      |              | 45.4 MB   | http://podcasts.nerdologues.com/poorchoicesshow/mattbarbera.mp3                                             |
    | Episode 161: A Tale of Two Marks                                         | 2012-05-31     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/py6237/marklogsdon.mp3          |      |              | 35.26 MB  | http://podcasts.nerdologues.com/poorchoicesshow/marklogsdon.mp3                                             |
    | June 2012: Family Matters                                                | 2012-06-01     | Your Stories         | http://yourstories.podbean.com/mf/feed/7926ih/June.mp3                     |      |              | 66.97 MB  | https://podcasts.nerdologues.com/yourstories/June.mp3                                                       |
    | Episode 162: BOOM…It’s Sam Super                                         | 2012-06-05     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/z7i43z/samsuper.mp3             |      |              | 28.67 MB  | http://podcasts.nerdologues.com/poorchoicesshow/samsuper.mp3                                                |
    | Episode 163: Act Like A Lady With Wes Perry                              | 2012-06-06     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/cqrw4/wesperry.mp3              |      |              | 29.71 MB  | http://podcasts.nerdologues.com/poorchoicesshow/wesperry.mp3                                                |
    | Episode 164: Going Viral with Dave Urlakis                               | 2012-06-12     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/i9yxzs/daveurlakis.mp3          |      |              | 30.73 MB  | http://podcasts.nerdologues.com/poorchoicesshow/daveurlakis.mp3                                             |
    | Episode 165: The Heart of John Hartman                                   | 2012-06-14     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/2t5g6u/johnhartman.mp3          |      |              | 31.09 MB  | http://podcasts.nerdologues.com/poorchoicesshow/johnhartman.mp3                                             |
    | BONUS: Live at Project Comic-Con, St. Louis                              | 2012-06-15     | Your Stories         | http://yourstories.podbean.com/mf/feed/tx4dd/StLouis.mp3                   |      |              | 17.52 MB  | https://podcasts.nerdologues.com/yourstories/StLouis.mp3                                                    |
    | Episode 166: Flying High with Drennen Quinn                              | 2012-06-19     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/t3wysm/drennenquinn.mp3         |      |              | 35.63 MB  | http://podcasts.nerdologues.com/poorchoicesshow/drennenquinn.mp3                                            |
    | Episode 167: Rich Baker is a Stand Up Guy                                | 2012-06-25     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/xwswdv/richbakernew.mp3         |      |              | 29.47 MB  | http://podcasts.nerdologues.com/poorchoicesshow/richbakernew.mp3                                            |
    | July 2012 Part 1: Friends in Low Places                                  | 2012-07-01     | Your Stories         | http://yourstories.podbean.com/mf/feed/hsd2ye/Julypart1.mp3                |      |              | 48.6 MB   | https://podcasts.nerdologues.com/yourstories/Julypart1.mp3                                                  |
    | Episode 168: Happy Nerd of July with Sammy Tamimi                        | 2012-07-03     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/s6mzu8/sammi.mp3                |      |              | 35.82 MB  | http://podcasts.nerdologues.com/poorchoicesshow/sammi.mp3                                                   |
    | Episode 169: Killing Comedy with Steph Cook                              | 2012-07-10     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/mharzt/stephcook.mp3            |      |              | 26.62 MB  | http://podcasts.nerdologues.com/poorchoicesshow/stephcook.mp3                                               |
    | Episode 170: Kill All Comedy                                             | 2012-07-12     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/62ghkc/killallcomedy.mp3        |      |              | 50.82 MB  | http://podcasts.nerdologues.com/poorchoicesshow/killallcomedy.mp3                                           |
    | July 2012 Part 2: Fight For Your Right                                   | 2012-07-15     | Your Stories         | http://yourstories.podbean.com/mf/feed/4v4ev6/Julypart2.mp3                |      |              | 40.8 MB   | https://podcasts.nerdologues.com/yourstories/Julypart2.mp3                                                  |
    | Episode 171: …and Twin with John Pantlind                                | 2012-07-17     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/d3brmg/johnpaintland.mp3        |      |              | 28.75 MB  | http://podcasts.nerdologues.com/poorchoicesshow/johnpaintland.mp3                                           |
    | Episode 172: A Declaration of Sovereignty with Clayton Margeson          | 2012-07-19     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/jw8hy/clayton.mp3               |      |              | 34.21 MB  | http://podcasts.nerdologues.com/poorchoicesshow/clayton.mp3                                                 |
    | Episode 173: My Man Tim Robinson                                         | 2012-07-24     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/z3428y/timrobinson.mp3          |      |              | 46.09 MB  | http://podcasts.nerdologues.com/poorchoicesshow/timrobinson.mp3                                             |
    | Episode 174: Going Cold Turkey With Ben Johnson                          | 2012-07-26     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/jzmah/benjohnson.mp3            |      |              | 33.33 MB  | http://podcasts.nerdologues.com/poorchoicesshow/benjohnson.mp3                                              |
    | Episode 175: Vermont is for Performers with Steve Waltien                | 2012-07-31     | Poor Choices Archive | http://poorchoicesshow.podbean.com/mf/feed/cxjfye/stevewaltein.mp3         |      |              | 39.59 MB  | http://podcasts.nerdologues.com/poorchoicesshow/stevewaltein.mp3                                            |
    | August 2012 Part 1: It’s The End of the World as We Know It              | 2012-08-01     | Your Stories         | http://yourstories.podbean.com/mf/feed/3icndu/AugustPart1.mp3              |      |              | 34.6 MB   | https://podcasts.nerdologues.com/yourstories/AugustPart1.mp3                                                |
