Feature: Video

  @api
  Scenario: Video nodes table
    Given I am logged in as a user with the "administrator" role
    When I visit "admin/content-migration/quotes"
    Then I should see the following table portion
      | ID   |                                                                    | Quotes (field_para_quotes:delta) | int_start_time | Quote                                                                                                                                              |
      | 198  | Chris Geiger: Why We Need the Man of Steel                         | 0                                | 0              | "Superman gets a bad rap; from me mainly."                                                                                                         |
      | 198  | Chris Geiger: Why We Need the Man of Steel                         | 1                                | 0              | Spiderman is a loser.                                                                                                                              |
      | 198  | Chris Geiger: Why We Need the Man of Steel                         | 2                                | 0              | He's that guy who does hot yoga before he goes to work; that you hate.                                                                             |
      | 232  | Allison MacWilliams-Brooks: My Dad & Star Trek                     | 0                                | 144            | “Once I found out my dad had wanted a boy, I decided it was going to be my personal project to be the son he never had.”                           |
      | 236  | Eric Garneau: Call to Adventure                                    | 0                                | 0              | "It's time to take this journey."                                                                                                                  |
      | 236  | Eric Garneau: Call to Adventure                                    | 1                                | 0              | "Why am I here anymore? Why do I need to stay in the suburbs?"                                                                                     |
      | 299  | Eric Garneau: Transformers Spotlight: Punch-Counterpunch           | 0                                | 0              | "In the multi-millennial war for Cyberton, Punch/Counterpunch was engineered to be the perfect spy."                                               |
      | 299  | Eric Garneau: Transformers Spotlight: Punch-Counterpunch           | 1                                | 0              | "I am obsessed with Transformers"                                                                                                                  |
      | 299  | Eric Garneau: Transformers Spotlight: Punch-Counterpunch           | 2                                | 0              | "I have been writing Transformers fan fiction since I was literally like five or six years old."                                                   |
      | 299  | Eric Garneau: Transformers Spotlight: Punch-Counterpunch           | 3                                | 0              | "This is what you need to do to make Masters of The Universe cool again."                                                                          |
      | 299  | Eric Garneau: Transformers Spotlight: Punch-Counterpunch           | 4                                | 0              | He can be an Autobot, or if you flip him around, he can be a Decepticon.                                                                           |
      | 299  | Eric Garneau: Transformers Spotlight: Punch-Counterpunch           | 5                                | 0              | "Bear with me, this gets a little deep."                                                                                                           |
      | 299  | Eric Garneau: Transformers Spotlight: Punch-Counterpunch           | 6                                | 0              | "But Punch/Counterpunch has a problem. He can no longer remember what side he's on"                                                                |
      | 299  | Eric Garneau: Transformers Spotlight: Punch-Counterpunch           | 7                                | 0              | "How did someone with such a dangerous function outlast all his peers?"                                                                            |
      | 299  | Eric Garneau: Transformers Spotlight: Punch-Counterpunch           | 8                                | 0              | "The action climaxes when Punch and Counterpunch come face to face in the midst of a decisive battle."                                             |
      | 299  | Eric Garneau: Transformers Spotlight: Punch-Counterpunch           | 9                                | 0              | "I wonder if this is the professional version of a girl being like 'Oh, I'm so busy this week."                                                    |
      | 320  | Chris Crotwell: Discovering an Author                              | 0                                | 0              | "It's that moment when you get 15 pages into a book and you get all fizzy inside... you say 'ohhhh.'"                                              |
      | 398  | Andrew Bentley: Role Models                                        | 0                                | 49             | "I'm far from the first nerd to machete my way through this particular jungle."                                                                    |
      | 398  | Andrew Bentley: Role Models                                        | 1                                | 210            | "Our out of control ethanol industry is by no means in need of further subside by way of human sacrifice."                                         |
      | 402  | Chris Geiger: Gotta Catch ‘Em All                                  | 0                                | 290            | "I got the destroyer of worlds on my team."                                                                                                        |
      | 402  | Chris Geiger: Gotta Catch ‘Em All                                  | 1                                | 306            | "I turned my Pokémon into real bastards."                                                                                                          |
      | 403  | Dwight & Eric: The Pokémon Theme                                   | 0                                | 0              | "To catch them is my real test, to train them is my cause."                                                                                        |
      | 442  | Dwight & Eric: Land of Confusion                                   | 0                                | 0              | "Superman where are you now?"                                                                                                                      |
      | 442  | Dwight & Eric: Land of Confusion                                   | 1                                | 0              | "Auk auk auk auk!"                                                                                                                                 |
      | 448  | Dwight, Eric & Claire: Zombie                                      | 0                                | 5              | "When I asked her to do this she said 'This is all I want to do with my life.'"                                                                    |
      | 477  | Kevin Reader & Chris Geiger: Dungeons & Dragons slam poetry        | 0                                | 0              | "On a die of 20, I am a 21."                                                                                                                       |
      | 507  | Bill Kenkel: On Sexuality and Productivity                         | 0                                | 0              | "If I ever find happiness with someone I will become a boring shell of a human being."                                                             |
      | 507  | Bill Kenkel: On Sexuality and Productivity                         | 1                                | 23             | I've tried to get away with a job that pays me to think about sex, as if that's something I wasn't going to do anyway.                             |
      | 507  | Bill Kenkel: On Sexuality and Productivity                         | 2                                | 40             | "Everything we do is because of sex"                                                                                                               |
      | 507  | Bill Kenkel: On Sexuality and Productivity                         | 3                                | 0              | "My parents decided to renew their faith in the middle of my puberty."                                                                             |
      | 507  | Bill Kenkel: On Sexuality and Productivity                         | 4                                | 138            | "I'm such a better person when I'm alone and miserable and striving."                                                                              |
      | 507  | Bill Kenkel: On Sexuality and Productivity                         | 5                                | 0              | "People are most successful... at their peak reproductive years because we are trying so hard to get laid."                                        |
      | 507  | Bill Kenkel: On Sexuality and Productivity                         | 6                                | 200            | "Once you get married your success just falls away."                                                                                               |
      | 507  | Bill Kenkel: On Sexuality and Productivity                         | 7                                | 237            | "Once you've pushed kids out of the house... why do you exist?"                                                                                    |
      | 507  | Bill Kenkel: On Sexuality and Productivity                         | 8                                | 300            | "If there's one benefit to being chronically single, it's that you get a lot of shit done."                                                        |
      | 531  | Nerdologues: Magneto Was Right                                     | 0                                | 181            | "Never again will I abide a nerd to be shamed by his nature. Never again! Never again!"                                                            |
      | 531  | Nerdologues: Magneto Was Right                                     | 1                                | 90             | "I think I'd be an evil mutant."                                                                                                                   |
      | 531  | Nerdologues: Magneto Was Right                                     | 2                                | 120            | "Bill, it's our responsibility to help the cook kids related to the X-Men's sense of alienation!"                                                  |
      | 550  | Steve Persch: Left Behind                                          | 0                                | 0              | "The Wyld Stallyns can go to hell, something tells me they will."                                                                                  |
      | 579  | Kevin Reader: Bad Reviews                                          | 0                                | 67             | "So I was driven to read by pizza."                                                                                                                |
      | 579  | Kevin Reader: Bad Reviews                                          | 1                                | 28             | "Hey, I bet you read a lot!"                                                                                                                       |
      | 579  | Kevin Reader: Bad Reviews                                          | 2                                | 235            | "Bar none, the worst book of poetry I have ever read."                                                                                             |
      | 579  | Kevin Reader: Bad Reviews                                          | 3                                | 247            | "The book has nothing to offer anybody, save disappointment."                                                                                      |
      | 579  | Kevin Reader: Bad Reviews                                          | 4                                | 258            | "I would classify this as bad children's literature if I were being kind."                                                                         |
      | 579  | Kevin Reader: Bad Reviews                                          | 5                                | 288            | "I had to actually call my wife to read along with me. They two of us were completely awestruck by the utter lack of substance the book offered."  |
      | 579  | Kevin Reader: Bad Reviews                                          | 6                                | 301            | "I strongly urge anyone buying this book to first purchase a Tom Green movie"                                                                      |
      | 583  | Alex Talavera: Crisis on Infinite Alexes                           | 0                                | 132            | "Everyone is trying to rob and/or kill you all the time."                                                                                          |
      | 583  | Alex Talavera: Crisis on Infinite Alexes                           | 1                                | 166            | I have reverse robbed a dude who robbed a friend of mine.                                                                                          |
      | 583  | Alex Talavera: Crisis on Infinite Alexes                           | 2                                | 190            | Later on, he got thrown out of a moving car on interstate 10.                                                                                      |
      | 583  | Alex Talavera: Crisis on Infinite Alexes                           | 3                                | 197            | There was a period of time where I slept with a sawed off shotgun under my mattress.                                                               |
      | 583  | Alex Talavera: Crisis on Infinite Alexes                           | 4                                | 218            | The odds of me being alive today are statistically negligible.                                                                                     |
      | 583  | Alex Talavera: Crisis on Infinite Alexes                           | 5                                | 324            | There are a thousand universes where I am dead.                                                                                                    |
      | 606  | Claire, Dwight, & Eric: Rebel Yell                                 | 0                                | 54             | "This is a side of Claire that we never get to see."                                                                                               |
      | 606  | Claire, Dwight, & Eric: Rebel Yell                                 | 1                                | 0              | "In the midnight hour she cried - 'more, more, more'"                                                                                              |
      | 606  | Claire, Dwight, & Eric: Rebel Yell                                 | 2                                | 0              | "With a rebel yell she cried - 'more, more, more'"                                                                                                 |
      | 616  | Joe Gennaro: 9-to-5er                                              | 0                                | 435            | "And sometimes, if I'm lucky, I get to go up on stage and be myself. And I can't think of anything I'd rather be."                                 |
      | 616  | Joe Gennaro: 9-to-5er                                              | 1                                | 132            | "I wanted to be everything."                                                                                                                       |
      | 616  | Joe Gennaro: 9-to-5er                                              | 2                                | 135            | "The first thing I remember wanting to be was a professional ghost buster."                                                                        |
      | 616  | Joe Gennaro: 9-to-5er                                              | 3                                | 163            | "I wanted to be a monster truck driver / scientist."                                                                                               |
      | 616  | Joe Gennaro: 9-to-5er                                              | 4                                | 179            | "Tell me that doesn't sound awesome and I will tell you that you are a liar."                                                                      |
      | 616  | Joe Gennaro: 9-to-5er                                              | 5                                | 329            | "Every day I acted like I didn't want to kill myself and every single person around me."                                                           |
      | 657  | Dwight & Eric: Everybody Talks                                     | 0                                | 0              | "It started with a whisper."                                                                                                                       |
      | 658  | Dwight, Eric, Claire & Sarah: Rebellion (Lies)                     | 0                                | 0              | "Come on baby, in our dreams we can live our misbehavior."                                                                                         |
      | 662  | Allison MacWilliams-Brooks Talavera: My Dad and Star Trek          | 0                                | 144            | “Once I found out my dad had wanted a boy, I decided it was going to be my personal project to be the son he never had.”                           |
      | 665  | Dwight & Eric: Wish You Were Here                                  | 0                                | 0              | "We're just two lost souls swimming in a fishbowl year after year."                                                                                |
      | 667  | Dwight & Eric: The Ballad of Serenity/Rocket Man                   | 0                                | 0              | "There's no place I can be since I found serenity."                                                                                                |
      | 668  | Mary Beth Smith: Helping                                           | 0                                | 0              | "In an alternate universe I could have been a personality scientist."                                                                              |
      | 669  | Matt Young: The Matts of Different Worlds                          | 0                                | 0              | "What am I doing on all those other planets?"                                                                                                      |
      | 670  | Kevin Budnik: Space Is Terrifying                                  | 0                                | 0              | "Imagine a lonely little kid up on the moon... like The Little Prince but sadder."                                                                 |
      | 671  | Mark Lancaster: "Oh, You Watch Star Trek?"                         | 0                                | 0              | "Oh, you watch Star Trek? Go away."                                                                                                                |
      | 672  | Jeremy Kanne: A Matter of Scale                                    | 0                                | 0              | "What is a million seconds?"                                                                                                                       |
      | 673  | Dwight & Eric: Star Trek Theme                                     | 0                                | 0              | "This star trek will go on forever!"                                                                                                               |
      | 675  | Dwight, Claire, & Eric: Yakko's Universe                           | 0                                | 0              | "We're just tiny little specks about the size of Mickey Rooney."                                                                                   |
      | 676  | Dwight & Eric: Walkin' on the Sun                                  | 0                                | 0              | "So don't delay, act now!"                                                                                                                         |
      | 677  | Julia Weiss: Alien Abduction                                       | 0                                | 0              | "Hitler got his dick wet."                                                                                                                         |
      | 678  | Drew Krehel: Perspective (via Carl Sagan)                          | 0                                | 0              | "The delusion that we have some privileged position in the universe is challenged by this point of pale light."                                    |
      | 679  | Jean Monfort: Universes of the Mind                                | 0                                | 0              | "The human mind can create an infinite number of universes within itself."                                                                         |
      | 680  | Sean Kelley: Space, Time, Distance, and Romance                    | 0                                | 0              | "I'm 19 and I just did an amazing improv show. I can have any woman I want!"                                                                       |
      | 681  | Christopher Kidder-Mostrom: I Killed Roger                         | 0                                | 0              | "Perhaps, self-delusionally, I wanted to believe Smurfette was real."                                                                              |
      | 682  | Claire & Eric: Across the Universe                                 | 0                                | 0              | "Jai guru deva om"                                                                                                                                 |
      | 693  | Cover Stories: Closer                                              | 0                                | 0              | "All I think of lately is how to get you underneath me."                                                                                           |
      | 694  | Cover Stories: House of Gold                                       | 0                                | 0              | "She asked me 'Son, when I grow old will you buy me a house of gold?'"                                                                             |
      | 695  | Eric Garneau: The Elliott Smith Tribute Concert / Ripchord         | 0                                | 0              | "Pull the ripchord; your ship has lost its sail."                                                                                                  |
      | 696  | Matthew Sudman: (Comics) Annual                                    | 0                                | 0              | "They're really an ode to failure."                                                                                                                |
      | 697  | Mary Zee: The Best Present I Ever Gave / She Saved the World a Lot | 0                                | 28             | "This kind of attention to detail is something you only see from best friends and schizophrenics."                                                 |
      | 842  | Cover Stories: Royals                                              | 0                                | 0              | "I cut my teeth on wedding rings in the movies."                                                                                                   |
      | 843  | Katie Keenan: Take Take Take                                       | 0                                | 0              | "That takes the cake."                                                                                                                             |
      | 844  | Mary Beth Smith: This Year                                         | 0                                | 0              | "I like keeping around melancholy songs and films to help me feel emotions instead of ignoring them."                                              |
      | 845  | Eric and Dwight: Drive All Night                                   | 0                                | 0              | "I swear I'd drive all night just to buy you some shoes."                                                                                          |
      | 846  | Cover Stories: Toe to Toe                                          | 0                                | 0              | "Who will be Goliath? And will you throw the stone?"                                                                                               |
      | 847  | Cover Stories: It's a Lovely Day                                   | 0                                | 0              | "It's been all right. I've had a lovely night with you."                                                                                           |
      | 848  | Cover Stories: Heart-Shaped Box                                    | 0                                | 0              | "Hey. Wait. I've got a new complaint."                                                                                                             |
      | 849  | Cover Stories: Alone                                               | 0                                | 0              | "I never really cared until I met you."                                                                                                            |
      | 850  | Chris Geiger: Ode to Will Riker                                    | 0                                | 0              | "You can really use this in any context where something might be smooth."                                                                          |
      | 878  | Johnny O'Mara: NPR vs. Dimension X                                 | 0                                | 0              | "I wrote this because the characters in this are the only two impressions I can do."                                                               |
      | 894  | Mary Beth Smith: Flight                                            | 0                                | 0              | "It's just fraught with irony."                                                                                                                    |
      | 1417 | Katie Johnston-Smith: Titanic                                      | 0                                | 95             | "In the mess I got to break myself in half, like the Titanic, and see what I'm really made of."                                                    |
      | 1417 | Katie Johnston-Smith: Titanic                                      | 1                                | 49             | I knew it must be a vital part of becoming a teen to see two blanketed actors hump each other while hiding in the bowels of a doomed luxury liner. |
      | 1548 | Cover Stories: Take Me to Church                                   | 0                                | 0              | "An incredible lead single and the album did just not live up to it."                                                                              |
      | 1581 | Cover Stories with Jim Snedeker: The Ghost of Tom Joad             | 0                                | 0              | "Inversions. Why? I don't think I know why. But it's something cool to think about."                                                               |
      | 1582 | Cover Stories with Jim Snedeker: All About That Bass               | 0                                | 0              | "All the right junk in all the right places."                                                                                                      |
      | 1758 | Katie Johnston-Smith: Mad                                          | 0                                | 27             | "Love's real spooky like a ghost."                                                                                                                 |
      | 1781 | Claire Friedman and Eric Garneau: Friendship                       | 0                                | 0              | "If you sing something, say something."                                                                                                            |
      | 1781 | Claire Friedman and Eric Garneau: Friendship                       | 1                                | 70             | "I had secretly always wanted to be in a band."                                                                                                    |
      | 1781 | Claire Friedman and Eric Garneau: Friendship                       | 2                                | 105            | "I just started trying really hard to act however Dwight would act."                                                                               |
      | 1781 | Claire Friedman and Eric Garneau: Friendship                       | 3                                | 164            | "I've got my Bruce Springsteen. Dwight has his Tenacious D."                                                                                       |
      | 1853 | Claire Friedman: Art Major                                         | 0                                | 60             | "It was the sixth Saturday in a row since I had been at school that I didn't have anything to do with anyone."                                     |
      | 1853 | Claire Friedman: Art Major                                         | 1                                | 127            | "It's like a history major but you only look at science. It's great. And never would be useful in any, ANY realm."                                 |
      | 1853 | Claire Friedman: Art Major                                         | 2                                | 320            | "So it's Claire getting advice from three different Claires."                                                                                      |
      | 1853 | Claire Friedman: Art Major                                         | 3                                | 392            | "And he said to me, 'Thank God, I didn't know what you were going to do with History of Science.'"                                                 |

